/**
 * Asset Mock Data
 *
 * Vietnamese company mock data for development and testing
 */

import type { Asset, AssetType, K8sCluster, K8sWorkload, ContainerImage, AssetFinding, Api, ApiEndpoint } from "../types";

// Helper to generate dates
const daysAgo = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

// Vietnamese domain assets
const domainAssets: Asset[] = [
  {
    id: "dom-001",
    type: "domain",
    name: "vingroup.vn",
    description: "Main corporate domain",
    status: "active",
    riskScore: 72,
    findingCount: 5,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      registrar: "VNNIC",
      expiryDate: "2026-05-15",
      nameservers: ["ns1.vingroup.vn", "ns2.vingroup.vn"],
    },
    tags: ["critical", "production"],
    firstSeen: daysAgo(365),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(365),
    updatedAt: daysAgo(1),
  },
  {
    id: "dom-002",
    type: "domain",
    name: "fpt.com.vn",
    description: "FPT Corporation main domain",
    status: "active",
    riskScore: 45,
    findingCount: 3,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      registrar: "VNNIC",
      expiryDate: "2025-12-20",
      nameservers: ["ns1.fpt.com.vn", "ns2.fpt.com.vn"],
    },
    tags: ["production"],
    firstSeen: daysAgo(300),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(300),
    updatedAt: daysAgo(2),
  },
  {
    id: "dom-003",
    type: "domain",
    name: "viettel.com.vn",
    description: "Viettel Group domain",
    status: "active",
    riskScore: 58,
    findingCount: 4,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      registrar: "VNNIC",
      expiryDate: "2026-08-10",
      nameservers: ["dns1.viettel.com.vn", "dns2.viettel.com.vn"],
    },
    tags: ["critical", "production"],
    firstSeen: daysAgo(400),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "dom-004",
    type: "domain",
    name: "techcombank.com.vn",
    description: "Techcombank domain",
    status: "active",
    riskScore: 82,
    findingCount: 7,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      registrar: "VNNIC",
      expiryDate: "2025-11-30",
      nameservers: ["ns1.techcombank.com.vn", "ns2.techcombank.com.vn"],
    },
    tags: ["critical", "banking", "production"],
    firstSeen: daysAgo(500),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(500),
    updatedAt: daysAgo(0),
  },
  {
    id: "dom-005",
    type: "domain",
    name: "vpbank.com.vn",
    description: "VPBank domain",
    status: "active",
    riskScore: 65,
    findingCount: 4,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      registrar: "VNNIC",
      expiryDate: "2026-03-15",
      nameservers: ["ns1.vpbank.com.vn", "ns2.vpbank.com.vn"],
    },
    tags: ["critical", "banking"],
    firstSeen: daysAgo(350),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(350),
    updatedAt: daysAgo(1),
  },
];

// Website assets
const websiteAssets: Asset[] = [
  {
    id: "web-001",
    type: "website",
    name: "portal.fpt.com.vn",
    description: "FPT Customer Portal",
    status: "active",
    riskScore: 45,
    findingCount: 3,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      technology: ["React", "Node.js", "PostgreSQL"],
      ssl: true,
      sslExpiry: "2025-06-15",
      httpStatus: 200,
    },
    tags: ["production", "customer-facing"],
    firstSeen: daysAgo(200),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(1),
  },
  {
    id: "web-002",
    type: "website",
    name: "ebanking.techcombank.com.vn",
    description: "Techcombank Internet Banking",
    status: "active",
    riskScore: 88,
    findingCount: 6,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      technology: ["Angular", "Java Spring", "Oracle"],
      ssl: true,
      sslExpiry: "2025-04-20",
      httpStatus: 200,
    },
    tags: ["critical", "banking", "customer-facing"],
    firstSeen: daysAgo(400),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(400),
    updatedAt: daysAgo(0),
  },
  {
    id: "web-003",
    type: "website",
    name: "shop.vinmart.vn",
    description: "VinMart E-commerce",
    status: "active",
    riskScore: 52,
    findingCount: 4,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      technology: ["Vue.js", "PHP Laravel", "MySQL"],
      ssl: true,
      sslExpiry: "2025-08-10",
      httpStatus: 200,
    },
    tags: ["production", "e-commerce"],
    firstSeen: daysAgo(180),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(2),
  },
  {
    id: "web-004",
    type: "website",
    name: "api.momo.vn",
    description: "MoMo API Gateway",
    status: "active",
    riskScore: 78,
    findingCount: 5,
    groupId: "grp-003",
    groupName: "Production - API Gateway",
    metadata: {
      technology: ["Go", "gRPC", "Redis"],
      ssl: true,
      sslExpiry: "2025-09-25",
      httpStatus: 200,
    },
    tags: ["critical", "api", "payment"],
    firstSeen: daysAgo(250),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(250),
    updatedAt: daysAgo(1),
  },
  {
    id: "web-005",
    type: "website",
    name: "admin.vnpt.vn",
    description: "VNPT Admin Portal",
    status: "active",
    riskScore: 35,
    findingCount: 2,
    groupId: "grp-007",
    groupName: "Internal Tools",
    metadata: {
      technology: ["React", "Python Django", "PostgreSQL"],
      ssl: true,
      sslExpiry: "2025-07-30",
      httpStatus: 200,
    },
    tags: ["internal", "admin"],
    firstSeen: daysAgo(150),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(150),
    updatedAt: daysAgo(3),
  },
];

// Service assets
const serviceAssets: Asset[] = [
  {
    id: "svc-001",
    type: "service",
    name: "SSH - 192.168.1.10:22",
    description: "Production SSH Server",
    status: "active",
    riskScore: 25,
    findingCount: 1,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      port: 22,
      protocol: "SSH",
      version: "OpenSSH 8.9",
      banner: "SSH-2.0-OpenSSH_8.9",
    },
    tags: ["production", "infrastructure"],
    firstSeen: daysAgo(400),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "svc-002",
    type: "service",
    name: "MySQL - db.internal.vn:3306",
    description: "Primary Database Server",
    status: "active",
    riskScore: 68,
    findingCount: 4,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      port: 3306,
      protocol: "MySQL",
      version: "MySQL 8.0.32",
    },
    tags: ["critical", "database"],
    firstSeen: daysAgo(450),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(450),
    updatedAt: daysAgo(0),
  },
  {
    id: "svc-003",
    type: "service",
    name: "Redis - cache.internal.vn:6379",
    description: "Redis Cache Cluster",
    status: "active",
    riskScore: 42,
    findingCount: 2,
    groupId: "grp-003",
    groupName: "Production - API Gateway",
    metadata: {
      port: 6379,
      protocol: "Redis",
      version: "Redis 7.0.11",
    },
    tags: ["production", "cache"],
    firstSeen: daysAgo(200),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(2),
  },
  {
    id: "svc-004",
    type: "service",
    name: "Kafka - kafka.internal.vn:9092",
    description: "Message Queue Cluster",
    status: "active",
    riskScore: 55,
    findingCount: 3,
    groupId: "grp-003",
    groupName: "Production - API Gateway",
    metadata: {
      port: 9092,
      protocol: "Kafka",
      version: "Apache Kafka 3.5.0",
    },
    tags: ["production", "messaging"],
    firstSeen: daysAgo(180),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(1),
  },
  {
    id: "svc-005",
    type: "service",
    name: "Elasticsearch - es.internal.vn:9200",
    description: "Log Search Cluster",
    status: "active",
    riskScore: 38,
    findingCount: 2,
    groupId: "grp-007",
    groupName: "Internal Tools",
    metadata: {
      port: 9200,
      protocol: "HTTP/Elasticsearch",
      version: "Elasticsearch 8.10.0",
    },
    tags: ["production", "logging"],
    firstSeen: daysAgo(150),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(150),
    updatedAt: daysAgo(3),
  },
];

// Repository assets
const repositoryAssets: Asset[] = [
  {
    id: "repo-001",
    type: "repository",
    name: "vingroup/core-banking-api",
    description: "Core Banking API Service",
    status: "active",
    riskScore: 62,
    findingCount: 4,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      provider: "github",
      visibility: "private",
      language: "Java",
      stars: 0,
    },
    tags: ["critical", "backend"],
    firstSeen: daysAgo(500),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(500),
    updatedAt: daysAgo(1),
  },
  {
    id: "repo-002",
    type: "repository",
    name: "fpt/ecommerce-frontend",
    description: "E-commerce Frontend Application",
    status: "active",
    riskScore: 35,
    findingCount: 2,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      provider: "gitlab",
      visibility: "private",
      language: "TypeScript",
      stars: 0,
    },
    tags: ["frontend", "production"],
    firstSeen: daysAgo(300),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(300),
    updatedAt: daysAgo(2),
  },
  {
    id: "repo-003",
    type: "repository",
    name: "viettel/infrastructure-terraform",
    description: "Infrastructure as Code",
    status: "active",
    riskScore: 78,
    findingCount: 6,
    groupId: "grp-006",
    groupName: "Cloud Infrastructure",
    metadata: {
      provider: "github",
      visibility: "private",
      language: "HCL",
      stars: 0,
    },
    tags: ["critical", "infrastructure"],
    firstSeen: daysAgo(250),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(250),
    updatedAt: daysAgo(0),
  },
  {
    id: "repo-004",
    type: "repository",
    name: "techcombank/mobile-app",
    description: "Mobile Banking Application",
    status: "active",
    riskScore: 85,
    findingCount: 7,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      provider: "bitbucket",
      visibility: "private",
      language: "Kotlin",
      stars: 0,
    },
    tags: ["critical", "mobile", "banking"],
    firstSeen: daysAgo(400),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "repo-005",
    type: "repository",
    name: "vpbank/docs-public",
    description: "Public Documentation",
    status: "active",
    riskScore: 15,
    findingCount: 1,
    groupId: "grp-005",
    groupName: "Partner Systems",
    metadata: {
      provider: "github",
      visibility: "public",
      language: "Markdown",
      stars: 12,
    },
    tags: ["documentation", "public"],
    firstSeen: daysAgo(100),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(100),
    updatedAt: daysAgo(5),
  },
];

// Cloud assets
const cloudAssets: Asset[] = [
  {
    id: "cloud-001",
    type: "cloud",
    name: "aws-prod-vpc-main",
    description: "Production VPC on AWS",
    status: "active",
    riskScore: 55,
    findingCount: 3,
    groupId: "grp-006",
    groupName: "Cloud Infrastructure",
    metadata: {
      cloudProvider: "aws",
      region: "ap-southeast-1",
      resourceType: "VPC",
    },
    tags: ["production", "network"],
    firstSeen: daysAgo(300),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "cloud-002",
    type: "cloud",
    name: "gcp-prod-gke-cluster",
    description: "Production Kubernetes Cluster",
    status: "active",
    riskScore: 72,
    findingCount: 5,
    groupId: "grp-006",
    groupName: "Cloud Infrastructure",
    metadata: {
      cloudProvider: "gcp",
      region: "asia-southeast1",
      resourceType: "GKE Cluster",
    },
    tags: ["critical", "kubernetes"],
    firstSeen: daysAgo(250),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(250),
    updatedAt: daysAgo(0),
  },
  {
    id: "cloud-003",
    type: "cloud",
    name: "azure-prod-sql-server",
    description: "Azure SQL Database Server",
    status: "active",
    riskScore: 68,
    findingCount: 4,
    groupId: "grp-006",
    groupName: "Cloud Infrastructure",
    metadata: {
      cloudProvider: "azure",
      region: "Southeast Asia",
      resourceType: "SQL Server",
    },
    tags: ["critical", "database"],
    firstSeen: daysAgo(200),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(2),
  },
  {
    id: "cloud-004",
    type: "cloud",
    name: "aws-prod-s3-assets",
    description: "Production Assets Storage",
    status: "active",
    riskScore: 42,
    findingCount: 2,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      cloudProvider: "aws",
      region: "ap-southeast-1",
      resourceType: "S3 Bucket",
    },
    tags: ["production", "storage"],
    firstSeen: daysAgo(180),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(3),
  },
  {
    id: "cloud-005",
    type: "cloud",
    name: "aws-staging-ec2-fleet",
    description: "Staging EC2 Instances",
    status: "active",
    riskScore: 28,
    findingCount: 1,
    groupId: "grp-004",
    groupName: "Staging Environment",
    metadata: {
      cloudProvider: "aws",
      region: "ap-southeast-1",
      resourceType: "EC2",
    },
    tags: ["staging", "compute"],
    firstSeen: daysAgo(150),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(150),
    updatedAt: daysAgo(1),
  },
];

// Host assets
const hostAssets: Asset[] = [
  {
    id: "host-001",
    type: "host",
    name: "prod-web-01",
    description: "Production web server",
    status: "active",
    riskScore: 45,
    findingCount: 3,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      ip: "10.0.1.10",
      hostname: "prod-web-01.internal.vn",
      os: "Ubuntu",
      osVersion: "22.04 LTS",
      architecture: "x64",
      cpuCores: 8,
      memoryGB: 32,
      isVirtual: true,
      hypervisor: "VMware ESXi",
      openPorts: [22, 80, 443],
    },
    tags: ["production", "web", "critical"],
    firstSeen: daysAgo(300),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "host-002",
    type: "host",
    name: "prod-db-01",
    description: "Primary database server",
    status: "active",
    riskScore: 72,
    findingCount: 5,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      ip: "10.0.1.20",
      hostname: "prod-db-01.internal.vn",
      os: "CentOS",
      osVersion: "8.5",
      architecture: "x64",
      cpuCores: 16,
      memoryGB: 64,
      isVirtual: false,
      openPorts: [22, 3306],
    },
    tags: ["production", "database", "critical"],
    firstSeen: daysAgo(400),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(400),
    updatedAt: daysAgo(0),
  },
  {
    id: "host-003",
    type: "host",
    name: "prod-app-01",
    description: "Application server",
    status: "active",
    riskScore: 38,
    findingCount: 2,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      ip: "10.0.2.10",
      hostname: "prod-app-01.internal.vn",
      os: "Ubuntu",
      osVersion: "20.04 LTS",
      architecture: "x64",
      cpuCores: 4,
      memoryGB: 16,
      isVirtual: true,
      hypervisor: "KVM",
      openPorts: [22, 8080, 8443],
    },
    tags: ["production", "application"],
    firstSeen: daysAgo(200),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(2),
  },
  {
    id: "host-004",
    type: "host",
    name: "staging-web-01",
    description: "Staging web server",
    status: "active",
    riskScore: 25,
    findingCount: 1,
    groupId: "grp-004",
    groupName: "Staging Environment",
    metadata: {
      ip: "10.1.1.10",
      hostname: "staging-web-01.internal.vn",
      os: "Ubuntu",
      osVersion: "22.04 LTS",
      architecture: "x64",
      cpuCores: 4,
      memoryGB: 8,
      isVirtual: true,
      hypervisor: "VMware ESXi",
      openPorts: [22, 80, 443],
    },
    tags: ["staging", "web"],
    firstSeen: daysAgo(150),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(150),
    updatedAt: daysAgo(3),
  },
  {
    id: "host-005",
    type: "host",
    name: "dc-windows-01",
    description: "Domain controller",
    status: "active",
    riskScore: 85,
    findingCount: 6,
    groupId: "grp-007",
    groupName: "Internal Tools",
    metadata: {
      ip: "10.0.0.5",
      hostname: "dc-windows-01.corp.vn",
      os: "Windows Server",
      osVersion: "2019",
      architecture: "x64",
      cpuCores: 8,
      memoryGB: 32,
      isVirtual: true,
      hypervisor: "Hyper-V",
      openPorts: [53, 88, 389, 636, 3389],
    },
    tags: ["critical", "infrastructure", "windows"],
    firstSeen: daysAgo(500),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(500),
    updatedAt: daysAgo(0),
  },
];

// Container assets
const containerAssets: Asset[] = [
  {
    id: "container-001",
    type: "container",
    name: "api-gateway",
    description: "API Gateway service",
    status: "active",
    riskScore: 42,
    findingCount: 2,
    groupId: "grp-003",
    groupName: "Production - API Gateway",
    metadata: {
      image: "nginx",
      imageTag: "1.25-alpine",
      registry: "docker.io",
      runtime: "containerd",
      orchestrator: "kubernetes",
      namespace: "production",
      cluster: "prod-gke-cluster",
      replicas: 3,
      cpuLimit: "500m",
      memoryLimit: "512Mi",
      containerPorts: [80, 443],
      vulnerabilities: 2,
    },
    tags: ["production", "gateway", "nginx"],
    firstSeen: daysAgo(180),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(1),
  },
  {
    id: "container-002",
    type: "container",
    name: "user-service",
    description: "User microservice",
    status: "active",
    riskScore: 55,
    findingCount: 3,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      image: "vingroup/user-service",
      imageTag: "v2.5.1",
      registry: "gcr.io",
      runtime: "containerd",
      orchestrator: "kubernetes",
      namespace: "production",
      cluster: "prod-gke-cluster",
      replicas: 5,
      cpuLimit: "1000m",
      memoryLimit: "1Gi",
      containerPorts: [8080],
      vulnerabilities: 5,
    },
    tags: ["production", "microservice", "java"],
    firstSeen: daysAgo(250),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(250),
    updatedAt: daysAgo(0),
  },
  {
    id: "container-003",
    type: "container",
    name: "payment-processor",
    description: "Payment processing service",
    status: "active",
    riskScore: 78,
    findingCount: 5,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      image: "vingroup/payment-processor",
      imageTag: "v3.1.0",
      registry: "gcr.io",
      runtime: "containerd",
      orchestrator: "kubernetes",
      namespace: "production",
      cluster: "prod-gke-cluster",
      replicas: 3,
      cpuLimit: "2000m",
      memoryLimit: "2Gi",
      containerPorts: [8443],
      vulnerabilities: 8,
    },
    tags: ["critical", "payment", "pci-dss"],
    firstSeen: daysAgo(300),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "container-004",
    type: "container",
    name: "redis-cache",
    description: "Redis caching layer",
    status: "active",
    riskScore: 32,
    findingCount: 1,
    groupId: "grp-003",
    groupName: "Production - API Gateway",
    metadata: {
      image: "redis",
      imageTag: "7.2-alpine",
      registry: "docker.io",
      runtime: "docker",
      orchestrator: "docker-swarm",
      namespace: "default",
      replicas: 1,
      cpuLimit: "500m",
      memoryLimit: "1Gi",
      containerPorts: [6379],
      vulnerabilities: 1,
    },
    tags: ["production", "cache", "redis"],
    firstSeen: daysAgo(200),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(2),
  },
  {
    id: "container-005",
    type: "container",
    name: "logging-agent",
    description: "Fluent Bit logging agent",
    status: "active",
    riskScore: 18,
    findingCount: 0,
    groupId: "grp-007",
    groupName: "Internal Tools",
    metadata: {
      image: "fluent/fluent-bit",
      imageTag: "2.1.10",
      registry: "docker.io",
      runtime: "containerd",
      orchestrator: "kubernetes",
      namespace: "monitoring",
      cluster: "prod-gke-cluster",
      replicas: 1,
      cpuLimit: "200m",
      memoryLimit: "256Mi",
      containerPorts: [2020, 24224],
      vulnerabilities: 0,
    },
    tags: ["monitoring", "logging"],
    firstSeen: daysAgo(100),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(100),
    updatedAt: daysAgo(5),
  },
];

// Database assets
const databaseAssets: Asset[] = [
  {
    id: "db-001",
    type: "database",
    name: "core-banking-db",
    description: "Core banking PostgreSQL database",
    status: "active",
    riskScore: 82,
    findingCount: 6,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      engine: "postgresql",
      dbVersion: "15.4",
      dbHost: "db.core-banking.internal.vn",
      dbPort: 5432,
      sizeGB: 500,
      encryption: true,
      backupEnabled: true,
      lastBackup: daysAgo(0),
      replication: "replica-set",
      connections: 150,
    },
    tags: ["critical", "production", "banking"],
    firstSeen: daysAgo(500),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(500),
    updatedAt: daysAgo(0),
  },
  {
    id: "db-002",
    type: "database",
    name: "ecommerce-mysql",
    description: "E-commerce MySQL database",
    status: "active",
    riskScore: 58,
    findingCount: 4,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      engine: "mysql",
      dbVersion: "8.0.35",
      dbHost: "db.ecommerce.internal.vn",
      dbPort: 3306,
      sizeGB: 200,
      encryption: true,
      backupEnabled: true,
      lastBackup: daysAgo(0),
      replication: "replica-set",
      connections: 80,
    },
    tags: ["production", "ecommerce"],
    firstSeen: daysAgo(300),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "db-003",
    type: "database",
    name: "analytics-mongodb",
    description: "Analytics MongoDB cluster",
    status: "active",
    riskScore: 45,
    findingCount: 2,
    groupId: "grp-007",
    groupName: "Internal Tools",
    metadata: {
      engine: "mongodb",
      dbVersion: "7.0.4",
      dbHost: "mongo.analytics.internal.vn",
      dbPort: 27017,
      sizeGB: 150,
      encryption: true,
      backupEnabled: true,
      lastBackup: daysAgo(1),
      replication: "cluster",
      connections: 45,
    },
    tags: ["production", "analytics"],
    firstSeen: daysAgo(200),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(2),
  },
  {
    id: "db-004",
    type: "database",
    name: "cache-redis",
    description: "Redis cache cluster",
    status: "active",
    riskScore: 28,
    findingCount: 1,
    groupId: "grp-003",
    groupName: "Production - API Gateway",
    metadata: {
      engine: "redis",
      dbVersion: "7.2.3",
      dbHost: "redis.cache.internal.vn",
      dbPort: 6379,
      sizeGB: 16,
      encryption: false,
      backupEnabled: false,
      replication: "cluster",
      connections: 200,
    },
    tags: ["production", "cache"],
    firstSeen: daysAgo(250),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(250),
    updatedAt: daysAgo(3),
  },
  {
    id: "db-005",
    type: "database",
    name: "staging-postgresql",
    description: "Staging PostgreSQL database",
    status: "active",
    riskScore: 35,
    findingCount: 2,
    groupId: "grp-004",
    groupName: "Staging Environment",
    metadata: {
      engine: "postgresql",
      dbVersion: "15.4",
      dbHost: "db.staging.internal.vn",
      dbPort: 5432,
      sizeGB: 50,
      encryption: false,
      backupEnabled: true,
      lastBackup: daysAgo(1),
      replication: "single",
      connections: 20,
    },
    tags: ["staging", "testing"],
    firstSeen: daysAgo(180),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(1),
  },
];

// Mobile app assets
const mobileAssets: Asset[] = [
  {
    id: "mobile-001",
    type: "mobile",
    name: "VinBank Mobile",
    description: "Mobile banking application",
    status: "active",
    riskScore: 75,
    findingCount: 5,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      platform: "cross-platform",
      bundleId: "vn.vingroup.banking",
      appVersion: "5.2.1",
      buildNumber: "521",
      minSdkVersion: "21",
      targetSdkVersion: "34",
      storeUrl: "https://play.google.com/store/apps/details?id=vn.vingroup.banking",
      lastRelease: daysAgo(14),
      downloads: 5000000,
      rating: 4.5,
      permissions: ["CAMERA", "FINGERPRINT", "LOCATION", "STORAGE"],
      sdks: ["React Native", "Firebase", "Sentry"],
    },
    tags: ["critical", "banking", "customer-facing"],
    firstSeen: daysAgo(400),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(400),
    updatedAt: daysAgo(14),
  },
  {
    id: "mobile-002",
    type: "mobile",
    name: "VinMart Shopping",
    description: "E-commerce shopping app",
    status: "active",
    riskScore: 52,
    findingCount: 3,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      platform: "android",
      bundleId: "vn.vinmart.shopping",
      appVersion: "3.8.0",
      buildNumber: "380",
      minSdkVersion: "23",
      targetSdkVersion: "34",
      storeUrl: "https://play.google.com/store/apps/details?id=vn.vinmart.shopping",
      lastRelease: daysAgo(7),
      downloads: 2000000,
      rating: 4.2,
      permissions: ["CAMERA", "LOCATION", "STORAGE", "NOTIFICATIONS"],
      sdks: ["Kotlin", "Firebase", "Google Maps"],
    },
    tags: ["production", "ecommerce"],
    firstSeen: daysAgo(300),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(300),
    updatedAt: daysAgo(7),
  },
  {
    id: "mobile-003",
    type: "mobile",
    name: "VinMart iOS",
    description: "VinMart iOS application",
    status: "active",
    riskScore: 48,
    findingCount: 2,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      platform: "ios",
      bundleId: "vn.vinmart.ios",
      appVersion: "3.7.5",
      buildNumber: "375",
      minSdkVersion: "14.0",
      targetSdkVersion: "17.0",
      storeUrl: "https://apps.apple.com/vn/app/vinmart/id123456789",
      lastRelease: daysAgo(10),
      downloads: 800000,
      rating: 4.4,
      permissions: ["Camera", "Location", "Photos", "Notifications"],
      sdks: ["Swift", "Firebase", "MapKit"],
    },
    tags: ["production", "ios", "ecommerce"],
    firstSeen: daysAgo(280),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(280),
    updatedAt: daysAgo(10),
  },
  {
    id: "mobile-004",
    type: "mobile",
    name: "Internal OPS App",
    description: "Internal operations app",
    status: "active",
    riskScore: 32,
    findingCount: 1,
    groupId: "grp-007",
    groupName: "Internal Tools",
    metadata: {
      platform: "android",
      bundleId: "vn.vingroup.ops",
      appVersion: "1.5.0",
      buildNumber: "150",
      minSdkVersion: "26",
      targetSdkVersion: "34",
      lastRelease: daysAgo(30),
      downloads: 500,
      rating: 4.0,
      permissions: ["CAMERA", "LOCATION"],
      sdks: ["Flutter", "Firebase"],
    },
    tags: ["internal", "operations"],
    firstSeen: daysAgo(150),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(150),
    updatedAt: daysAgo(30),
  },
  {
    id: "mobile-005",
    type: "mobile",
    name: "Partner Portal",
    description: "Partner mobile portal",
    status: "pending",
    riskScore: 25,
    findingCount: 0,
    groupId: "grp-005",
    groupName: "Partner Systems",
    metadata: {
      platform: "cross-platform",
      bundleId: "vn.vingroup.partner",
      appVersion: "1.0.0-beta",
      buildNumber: "100",
      minSdkVersion: "21",
      targetSdkVersion: "34",
      lastRelease: daysAgo(60),
      downloads: 100,
      permissions: ["CAMERA", "STORAGE"],
      sdks: ["React Native", "Firebase"],
    },
    tags: ["beta", "partner"],
    firstSeen: daysAgo(60),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
];

// Credential leak assets
const credentialAssets: Asset[] = [
  {
    id: "cred-001",
    type: "credential",
    name: "admin@vingroup.vn",
    description: "Leaked admin credentials",
    status: "active",
    riskScore: 95,
    findingCount: 1,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      source: "Data breach - DarkWeb",
      username: "admin@vingroup.vn",
      leakDate: "2024-08-15",
    },
    tags: ["critical", "credential-leak"],
    firstSeen: daysAgo(120),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(120),
    updatedAt: daysAgo(0),
  },
  {
    id: "cred-002",
    type: "credential",
    name: "developer@fpt.com.vn",
    description: "Developer account exposed",
    status: "active",
    riskScore: 75,
    findingCount: 1,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      source: "GitHub commit history",
      username: "developer@fpt.com.vn",
      leakDate: "2024-09-20",
    },
    tags: ["high", "credential-leak"],
    firstSeen: daysAgo(90),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(90),
    updatedAt: daysAgo(1),
  },
  {
    id: "cred-003",
    type: "credential",
    name: "api-key-techcombank",
    description: "API key leaked in public repo",
    status: "pending",
    riskScore: 88,
    findingCount: 1,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      source: "Public GitHub repository",
      username: "service-account",
      leakDate: "2024-10-05",
    },
    tags: ["critical", "api-key-leak"],
    firstSeen: daysAgo(60),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(60),
    updatedAt: daysAgo(2),
  },
  {
    id: "cred-004",
    type: "credential",
    name: "db-admin@vpbank.vn",
    description: "Database admin credentials",
    status: "completed",
    riskScore: 45,
    findingCount: 1,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      source: "Pastebin leak",
      username: "db-admin@vpbank.vn",
      leakDate: "2024-06-10",
    },
    tags: ["resolved", "credential-leak"],
    firstSeen: daysAgo(180),
    lastSeen: daysAgo(30),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(30),
  },
  {
    id: "cred-005",
    type: "credential",
    name: "ops@viettel.com.vn",
    description: "Operations team credentials",
    status: "active",
    riskScore: 65,
    findingCount: 1,
    groupId: "grp-006",
    groupName: "Cloud Infrastructure",
    metadata: {
      source: "Credential stuffing attack",
      username: "ops@viettel.com.vn",
      leakDate: "2024-11-01",
    },
    tags: ["high", "credential-leak"],
    firstSeen: daysAgo(45),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(45),
    updatedAt: daysAgo(1),
  },
];

// ============================================
// API Assets
// ============================================

export const apiAssets: Api[] = [
  {
    id: "api-001",
    name: "Core Banking API",
    description: "Core banking services API for account management and transactions",
    type: "rest",
    baseUrl: "https://api.vinbank.vn/v2",
    version: "2.5.0",
    authType: "oauth2",
    status: "active",
    endpointCount: 45,
    documentationUrl: "https://docs.vinbank.vn/api",
    openApiSpec: true,
    owner: "Banking Team",
    team: "Core Banking",
    riskScore: 78,
    findingCount: 6,
    requestsPerDay: 1500000,
    avgResponseTime: 85,
    errorRate: 0.02,
    tlsVersion: "TLS 1.3",
    corsEnabled: true,
    rateLimitEnabled: true,
    rateLimit: 1000,
    createdAt: daysAgo(500),
    lastSeen: daysAgo(0),
    lastActivity: daysAgo(0),
  },
  {
    id: "api-002",
    name: "Payment Gateway",
    description: "Payment processing and merchant services API",
    type: "rest",
    baseUrl: "https://payments.vinbank.vn/api/v1",
    version: "1.8.2",
    authType: "jwt",
    status: "active",
    endpointCount: 28,
    documentationUrl: "https://docs.vinbank.vn/payments",
    openApiSpec: true,
    owner: "Payment Team",
    team: "Payments",
    riskScore: 85,
    findingCount: 8,
    requestsPerDay: 800000,
    avgResponseTime: 120,
    errorRate: 0.01,
    tlsVersion: "TLS 1.3",
    corsEnabled: false,
    rateLimitEnabled: true,
    rateLimit: 500,
    createdAt: daysAgo(400),
    lastSeen: daysAgo(0),
    lastActivity: daysAgo(0),
  },
  {
    id: "api-003",
    name: "User Management GraphQL",
    description: "GraphQL API for user profile and authentication",
    type: "graphql",
    baseUrl: "https://api.vingroup.vn/graphql",
    version: "3.0.0",
    authType: "jwt",
    status: "active",
    endpointCount: 1,
    documentationUrl: "https://docs.vingroup.vn/graphql",
    openApiSpec: false,
    owner: "Platform Team",
    team: "Identity",
    riskScore: 62,
    findingCount: 4,
    requestsPerDay: 500000,
    avgResponseTime: 95,
    errorRate: 0.03,
    tlsVersion: "TLS 1.3",
    corsEnabled: true,
    rateLimitEnabled: true,
    rateLimit: 2000,
    createdAt: daysAgo(300),
    lastSeen: daysAgo(0),
    lastActivity: daysAgo(0),
  },
  {
    id: "api-004",
    name: "Real-time Notifications",
    description: "WebSocket API for push notifications and live updates",
    type: "websocket",
    baseUrl: "wss://ws.vingroup.vn",
    version: "1.2.0",
    authType: "jwt",
    status: "active",
    endpointCount: 5,
    openApiSpec: false,
    owner: "Platform Team",
    team: "Notifications",
    riskScore: 45,
    findingCount: 2,
    requestsPerDay: 2000000,
    avgResponseTime: 15,
    errorRate: 0.005,
    tlsVersion: "TLS 1.3",
    corsEnabled: true,
    rateLimitEnabled: false,
    createdAt: daysAgo(200),
    lastSeen: daysAgo(0),
    lastActivity: daysAgo(0),
  },
  {
    id: "api-005",
    name: "E-commerce API",
    description: "Product catalog, cart, and order management",
    type: "rest",
    baseUrl: "https://api.vinmart.vn/v3",
    version: "3.2.1",
    authType: "api_key",
    status: "active",
    endpointCount: 67,
    documentationUrl: "https://developer.vinmart.vn",
    openApiSpec: true,
    owner: "E-commerce Team",
    team: "VinMart",
    riskScore: 52,
    findingCount: 3,
    requestsPerDay: 1200000,
    avgResponseTime: 75,
    errorRate: 0.025,
    tlsVersion: "TLS 1.2",
    corsEnabled: true,
    rateLimitEnabled: true,
    rateLimit: 3000,
    createdAt: daysAgo(350),
    lastSeen: daysAgo(0),
    lastActivity: daysAgo(0),
  },
  {
    id: "api-006",
    name: "Analytics gRPC Service",
    description: "High-performance analytics data streaming",
    type: "grpc",
    baseUrl: "grpc://analytics.vingroup.vn:443",
    version: "2.0.0",
    authType: "mtls",
    status: "active",
    endpointCount: 12,
    openApiSpec: false,
    owner: "Data Team",
    team: "Analytics",
    riskScore: 35,
    findingCount: 1,
    requestsPerDay: 5000000,
    avgResponseTime: 25,
    errorRate: 0.001,
    tlsVersion: "TLS 1.3",
    corsEnabled: false,
    rateLimitEnabled: false,
    createdAt: daysAgo(180),
    lastSeen: daysAgo(0),
    lastActivity: daysAgo(0),
  },
  {
    id: "api-007",
    name: "Legacy SOAP Service",
    description: "Legacy enterprise integration services",
    type: "soap",
    baseUrl: "https://legacy.vingroup.vn/ws",
    version: "1.0.0",
    authType: "basic",
    status: "deprecated",
    endpointCount: 8,
    documentationUrl: "https://wiki.vingroup.vn/legacy-api",
    openApiSpec: false,
    owner: "IT Operations",
    team: "Legacy Systems",
    riskScore: 72,
    findingCount: 5,
    requestsPerDay: 50000,
    avgResponseTime: 350,
    errorRate: 0.08,
    tlsVersion: "TLS 1.2",
    corsEnabled: false,
    rateLimitEnabled: false,
    createdAt: daysAgo(1000),
    lastSeen: daysAgo(0),
    lastActivity: daysAgo(1),
  },
  {
    id: "api-008",
    name: "Mobile Backend API",
    description: "Backend for mobile applications",
    type: "rest",
    baseUrl: "https://mobile-api.vingroup.vn/v2",
    version: "2.1.0",
    authType: "oauth2",
    status: "active",
    endpointCount: 38,
    documentationUrl: "https://docs.vingroup.vn/mobile-api",
    openApiSpec: true,
    owner: "Mobile Team",
    team: "Mobile",
    riskScore: 58,
    findingCount: 3,
    requestsPerDay: 900000,
    avgResponseTime: 65,
    errorRate: 0.015,
    tlsVersion: "TLS 1.3",
    corsEnabled: true,
    rateLimitEnabled: true,
    rateLimit: 1500,
    createdAt: daysAgo(250),
    lastSeen: daysAgo(0),
    lastActivity: daysAgo(0),
  },
  {
    id: "api-009",
    name: "Partner Integration API",
    description: "External partner and B2B integration services",
    type: "rest",
    baseUrl: "https://partner-api.vingroup.vn/v1",
    version: "1.5.0",
    authType: "oauth2",
    status: "active",
    endpointCount: 22,
    documentationUrl: "https://partner.vingroup.vn/docs",
    openApiSpec: true,
    owner: "Partnership Team",
    team: "B2B",
    riskScore: 48,
    findingCount: 2,
    requestsPerDay: 150000,
    avgResponseTime: 110,
    errorRate: 0.02,
    tlsVersion: "TLS 1.3",
    corsEnabled: false,
    rateLimitEnabled: true,
    rateLimit: 200,
    createdAt: daysAgo(150),
    lastSeen: daysAgo(0),
    lastActivity: daysAgo(0),
  },
  {
    id: "api-010",
    name: "Internal Admin API",
    description: "Internal administration and management API",
    type: "rest",
    baseUrl: "https://admin-api.internal.vn/v1",
    version: "1.0.5",
    authType: "jwt",
    status: "development",
    endpointCount: 15,
    openApiSpec: true,
    owner: "Platform Team",
    team: "Internal Tools",
    riskScore: 42,
    findingCount: 1,
    requestsPerDay: 10000,
    avgResponseTime: 55,
    errorRate: 0.04,
    tlsVersion: "TLS 1.3",
    corsEnabled: true,
    rateLimitEnabled: false,
    createdAt: daysAgo(60),
    lastSeen: daysAgo(0),
    lastActivity: daysAgo(0),
  },
];

// API Endpoints
export const apiEndpoints: ApiEndpoint[] = [
  // Core Banking API endpoints
  {
    id: "endpoint-001",
    apiId: "api-001",
    apiName: "Core Banking API",
    path: "/accounts",
    method: "GET",
    description: "List all user accounts",
    parameters: [
      { name: "page", in: "query", required: false, type: "integer" },
      { name: "limit", in: "query", required: false, type: "integer" },
    ],
    responseType: "application/json",
    authenticated: true,
    deprecated: false,
    riskScore: 45,
    findingCount: 0,
    lastCalled: daysAgo(0),
    avgResponseTime: 65,
    errorRate: 0.01,
    createdAt: daysAgo(500),
    lastSeen: daysAgo(0),
  },
  {
    id: "endpoint-002",
    apiId: "api-001",
    apiName: "Core Banking API",
    path: "/accounts/{accountId}",
    method: "GET",
    description: "Get account details",
    parameters: [
      { name: "accountId", in: "path", required: true, type: "string" },
    ],
    responseType: "application/json",
    authenticated: true,
    deprecated: false,
    riskScore: 55,
    findingCount: 1,
    lastCalled: daysAgo(0),
    avgResponseTime: 45,
    errorRate: 0.005,
    createdAt: daysAgo(500),
    lastSeen: daysAgo(0),
  },
  {
    id: "endpoint-003",
    apiId: "api-001",
    apiName: "Core Banking API",
    path: "/transfers",
    method: "POST",
    description: "Create a new transfer",
    parameters: [
      { name: "body", in: "body", required: true, type: "TransferRequest" },
    ],
    responseType: "application/json",
    authenticated: true,
    deprecated: false,
    riskScore: 85,
    findingCount: 2,
    lastCalled: daysAgo(0),
    avgResponseTime: 120,
    errorRate: 0.02,
    createdAt: daysAgo(500),
    lastSeen: daysAgo(0),
  },
  {
    id: "endpoint-004",
    apiId: "api-001",
    apiName: "Core Banking API",
    path: "/transactions",
    method: "GET",
    description: "List transaction history",
    parameters: [
      { name: "accountId", in: "query", required: true, type: "string" },
      { name: "from", in: "query", required: false, type: "date" },
      { name: "to", in: "query", required: false, type: "date" },
    ],
    responseType: "application/json",
    authenticated: true,
    deprecated: false,
    riskScore: 65,
    findingCount: 1,
    lastCalled: daysAgo(0),
    avgResponseTime: 95,
    errorRate: 0.015,
    createdAt: daysAgo(500),
    lastSeen: daysAgo(0),
  },
  // Payment Gateway endpoints
  {
    id: "endpoint-005",
    apiId: "api-002",
    apiName: "Payment Gateway",
    path: "/payments/initiate",
    method: "POST",
    description: "Initiate a payment transaction",
    parameters: [
      { name: "body", in: "body", required: true, type: "PaymentRequest" },
    ],
    responseType: "application/json",
    authenticated: true,
    deprecated: false,
    riskScore: 92,
    findingCount: 3,
    lastCalled: daysAgo(0),
    avgResponseTime: 150,
    errorRate: 0.008,
    createdAt: daysAgo(400),
    lastSeen: daysAgo(0),
  },
  {
    id: "endpoint-006",
    apiId: "api-002",
    apiName: "Payment Gateway",
    path: "/payments/{paymentId}/status",
    method: "GET",
    description: "Get payment status",
    parameters: [
      { name: "paymentId", in: "path", required: true, type: "string" },
    ],
    responseType: "application/json",
    authenticated: true,
    deprecated: false,
    riskScore: 45,
    findingCount: 0,
    lastCalled: daysAgo(0),
    avgResponseTime: 35,
    errorRate: 0.005,
    createdAt: daysAgo(400),
    lastSeen: daysAgo(0),
  },
  {
    id: "endpoint-007",
    apiId: "api-002",
    apiName: "Payment Gateway",
    path: "/refunds",
    method: "POST",
    description: "Process refund request",
    parameters: [
      { name: "body", in: "body", required: true, type: "RefundRequest" },
    ],
    responseType: "application/json",
    authenticated: true,
    deprecated: false,
    riskScore: 88,
    findingCount: 2,
    lastCalled: daysAgo(0),
    avgResponseTime: 180,
    errorRate: 0.012,
    createdAt: daysAgo(400),
    lastSeen: daysAgo(0),
  },
  // E-commerce API endpoints
  {
    id: "endpoint-008",
    apiId: "api-005",
    apiName: "E-commerce API",
    path: "/products",
    method: "GET",
    description: "List products",
    parameters: [
      { name: "category", in: "query", required: false, type: "string" },
      { name: "page", in: "query", required: false, type: "integer" },
    ],
    responseType: "application/json",
    authenticated: false,
    deprecated: false,
    riskScore: 25,
    findingCount: 0,
    lastCalled: daysAgo(0),
    avgResponseTime: 55,
    errorRate: 0.02,
    createdAt: daysAgo(350),
    lastSeen: daysAgo(0),
  },
  {
    id: "endpoint-009",
    apiId: "api-005",
    apiName: "E-commerce API",
    path: "/cart",
    method: "POST",
    description: "Add item to cart",
    parameters: [
      { name: "body", in: "body", required: true, type: "CartItem" },
    ],
    responseType: "application/json",
    authenticated: true,
    deprecated: false,
    riskScore: 42,
    findingCount: 1,
    lastCalled: daysAgo(0),
    avgResponseTime: 45,
    errorRate: 0.018,
    createdAt: daysAgo(350),
    lastSeen: daysAgo(0),
  },
  {
    id: "endpoint-010",
    apiId: "api-005",
    apiName: "E-commerce API",
    path: "/orders",
    method: "POST",
    description: "Create new order",
    parameters: [
      { name: "body", in: "body", required: true, type: "OrderRequest" },
    ],
    responseType: "application/json",
    authenticated: true,
    deprecated: false,
    riskScore: 68,
    findingCount: 1,
    lastCalled: daysAgo(0),
    avgResponseTime: 120,
    errorRate: 0.025,
    createdAt: daysAgo(350),
    lastSeen: daysAgo(0),
  },
  // Mobile Backend API endpoints
  {
    id: "endpoint-011",
    apiId: "api-008",
    apiName: "Mobile Backend API",
    path: "/auth/login",
    method: "POST",
    description: "User login",
    parameters: [
      { name: "body", in: "body", required: true, type: "LoginRequest" },
    ],
    responseType: "application/json",
    authenticated: false,
    deprecated: false,
    riskScore: 75,
    findingCount: 2,
    lastCalled: daysAgo(0),
    avgResponseTime: 85,
    errorRate: 0.03,
    createdAt: daysAgo(250),
    lastSeen: daysAgo(0),
  },
  {
    id: "endpoint-012",
    apiId: "api-008",
    apiName: "Mobile Backend API",
    path: "/auth/refresh",
    method: "POST",
    description: "Refresh access token",
    parameters: [
      { name: "Authorization", in: "header", required: true, type: "string" },
    ],
    responseType: "application/json",
    authenticated: true,
    deprecated: false,
    riskScore: 55,
    findingCount: 0,
    lastCalled: daysAgo(0),
    avgResponseTime: 35,
    errorRate: 0.01,
    createdAt: daysAgo(250),
    lastSeen: daysAgo(0),
  },
  // Legacy SOAP Service (deprecated endpoints)
  {
    id: "endpoint-013",
    apiId: "api-007",
    apiName: "Legacy SOAP Service",
    path: "/CustomerService",
    method: "POST",
    description: "Legacy customer service SOAP endpoint",
    responseType: "text/xml",
    authenticated: true,
    deprecated: true,
    riskScore: 82,
    findingCount: 3,
    lastCalled: daysAgo(1),
    avgResponseTime: 450,
    errorRate: 0.1,
    createdAt: daysAgo(1000),
    lastSeen: daysAgo(1),
  },
  {
    id: "endpoint-014",
    apiId: "api-007",
    apiName: "Legacy SOAP Service",
    path: "/OrderService",
    method: "POST",
    description: "Legacy order service SOAP endpoint",
    responseType: "text/xml",
    authenticated: true,
    deprecated: true,
    riskScore: 78,
    findingCount: 2,
    lastCalled: daysAgo(2),
    avgResponseTime: 380,
    errorRate: 0.08,
    createdAt: daysAgo(1000),
    lastSeen: daysAgo(2),
  },
];

// API Findings
const apiFindings: AssetFinding[] = [
  {
    id: "finding-api-001",
    type: "vulnerability",
    severity: "critical",
    status: "open",
    title: "SQL Injection in transfer endpoint",
    description: "The /transfers endpoint is vulnerable to SQL injection via the accountId parameter.",
    assetId: "api-001",
    assetName: "Core Banking API",
    assetType: "api",
    cveId: "CVE-2024-5678",
    cvssScore: 9.8,
    cweId: "CWE-89",
    remediation: "Use parameterized queries and input validation.",
    references: ["https://owasp.org/www-community/attacks/SQL_Injection"],
    firstSeen: daysAgo(5),
    lastSeen: daysAgo(0),
  },
  {
    id: "finding-api-002",
    type: "misconfiguration",
    severity: "high",
    status: "open",
    title: "Missing rate limiting on payment endpoint",
    description: "The /payments/initiate endpoint lacks proper rate limiting, allowing potential abuse.",
    assetId: "api-002",
    assetName: "Payment Gateway",
    assetType: "api",
    rule: "API-SEC-001",
    remediation: "Implement rate limiting with appropriate thresholds.",
    firstSeen: daysAgo(14),
    lastSeen: daysAgo(0),
  },
  {
    id: "finding-api-003",
    type: "misconfiguration",
    severity: "high",
    status: "in_progress",
    title: "Excessive data exposure in response",
    description: "API responses include sensitive data fields that should be filtered.",
    assetId: "api-002",
    assetName: "Payment Gateway",
    assetType: "api",
    rule: "API-SEC-003",
    remediation: "Implement response filtering to remove sensitive data.",
    firstSeen: daysAgo(30),
    lastSeen: daysAgo(0),
  },
  {
    id: "finding-api-004",
    type: "vulnerability",
    severity: "medium",
    status: "open",
    title: "Broken authentication in refresh token",
    description: "Refresh tokens don't expire properly, allowing indefinite session extension.",
    assetId: "api-008",
    assetName: "Mobile Backend API",
    assetType: "api",
    cweId: "CWE-613",
    remediation: "Implement proper token rotation and expiration.",
    firstSeen: daysAgo(21),
    lastSeen: daysAgo(0),
  },
  {
    id: "finding-api-005",
    type: "misconfiguration",
    severity: "critical",
    status: "open",
    title: "No authentication on SOAP endpoint",
    description: "Legacy SOAP endpoint accepts requests without proper authentication.",
    assetId: "api-007",
    assetName: "Legacy SOAP Service",
    assetType: "api",
    rule: "API-AUTH-001",
    remediation: "Implement WS-Security or migrate to modern REST API with OAuth.",
    firstSeen: daysAgo(60),
    lastSeen: daysAgo(0),
  },
];

// ============================================
// Kubernetes Resources
// ============================================

// K8s Clusters
export const k8sClusters: K8sCluster[] = [
  {
    id: "cluster-001",
    name: "prod-gke-cluster",
    provider: "gke",
    version: "1.28.5-gke.1200",
    region: "asia-southeast1",
    nodeCount: 5,
    namespaceCount: 12,
    workloadCount: 45,
    podCount: 156,
    status: "healthy",
    riskScore: 65,
    findingCount: 8,
    apiServerUrl: "https://35.240.10.25",
    createdAt: daysAgo(300),
    lastSeen: daysAgo(0),
  },
  {
    id: "cluster-002",
    name: "staging-eks-cluster",
    provider: "eks",
    version: "1.28",
    region: "ap-southeast-1",
    nodeCount: 3,
    namespaceCount: 6,
    workloadCount: 23,
    podCount: 67,
    status: "healthy",
    riskScore: 42,
    findingCount: 4,
    apiServerUrl: "https://eks.ap-southeast-1.amazonaws.com",
    createdAt: daysAgo(200),
    lastSeen: daysAgo(0),
  },
  {
    id: "cluster-003",
    name: "dev-k3s-cluster",
    provider: "k3s",
    version: "1.27.8+k3s1",
    nodeCount: 2,
    namespaceCount: 4,
    workloadCount: 15,
    podCount: 34,
    status: "warning",
    riskScore: 55,
    findingCount: 6,
    createdAt: daysAgo(150),
    lastSeen: daysAgo(0),
  },
];

// K8s Workloads
export const k8sWorkloads: K8sWorkload[] = [
  {
    id: "workload-001",
    name: "api-gateway",
    type: "deployment",
    clusterId: "cluster-001",
    clusterName: "prod-gke-cluster",
    namespace: "production",
    replicas: 3,
    readyReplicas: 3,
    images: ["nginx:1.25-alpine"],
    labels: { app: "api-gateway", tier: "frontend" },
    status: "running",
    riskScore: 42,
    findingCount: 2,
    cpuRequest: "250m",
    cpuLimit: "500m",
    memoryRequest: "256Mi",
    memoryLimit: "512Mi",
    createdAt: daysAgo(180),
    lastSeen: daysAgo(0),
  },
  {
    id: "workload-002",
    name: "user-service",
    type: "deployment",
    clusterId: "cluster-001",
    clusterName: "prod-gke-cluster",
    namespace: "production",
    replicas: 5,
    readyReplicas: 5,
    images: ["gcr.io/vingroup/user-service:v2.5.1"],
    labels: { app: "user-service", tier: "backend" },
    status: "running",
    riskScore: 55,
    findingCount: 3,
    cpuRequest: "500m",
    cpuLimit: "1000m",
    memoryRequest: "512Mi",
    memoryLimit: "1Gi",
    createdAt: daysAgo(250),
    lastSeen: daysAgo(0),
  },
  {
    id: "workload-003",
    name: "payment-processor",
    type: "deployment",
    clusterId: "cluster-001",
    clusterName: "prod-gke-cluster",
    namespace: "production",
    replicas: 3,
    readyReplicas: 3,
    images: ["gcr.io/vingroup/payment-processor:v3.1.0"],
    labels: { app: "payment-processor", tier: "backend", pci: "true" },
    status: "running",
    riskScore: 78,
    findingCount: 5,
    cpuRequest: "1000m",
    cpuLimit: "2000m",
    memoryRequest: "1Gi",
    memoryLimit: "2Gi",
    createdAt: daysAgo(300),
    lastSeen: daysAgo(0),
  },
  {
    id: "workload-004",
    name: "redis-cache",
    type: "statefulset",
    clusterId: "cluster-001",
    clusterName: "prod-gke-cluster",
    namespace: "production",
    replicas: 3,
    readyReplicas: 3,
    images: ["redis:7.2-alpine"],
    labels: { app: "redis", tier: "cache" },
    status: "running",
    riskScore: 32,
    findingCount: 1,
    cpuRequest: "250m",
    cpuLimit: "500m",
    memoryRequest: "512Mi",
    memoryLimit: "1Gi",
    createdAt: daysAgo(200),
    lastSeen: daysAgo(0),
  },
  {
    id: "workload-005",
    name: "fluent-bit",
    type: "daemonset",
    clusterId: "cluster-001",
    clusterName: "prod-gke-cluster",
    namespace: "monitoring",
    replicas: 5,
    readyReplicas: 5,
    images: ["fluent/fluent-bit:2.1.10"],
    labels: { app: "fluent-bit", tier: "logging" },
    status: "running",
    riskScore: 18,
    findingCount: 0,
    cpuRequest: "100m",
    cpuLimit: "200m",
    memoryRequest: "128Mi",
    memoryLimit: "256Mi",
    createdAt: daysAgo(100),
    lastSeen: daysAgo(0),
  },
  {
    id: "workload-006",
    name: "backup-job",
    type: "cronjob",
    clusterId: "cluster-001",
    clusterName: "prod-gke-cluster",
    namespace: "production",
    replicas: 1,
    readyReplicas: 0,
    images: ["gcr.io/vingroup/backup-tool:v1.0.0"],
    labels: { app: "backup", tier: "maintenance" },
    status: "pending",
    riskScore: 25,
    findingCount: 1,
    cpuLimit: "500m",
    memoryLimit: "512Mi",
    createdAt: daysAgo(60),
    lastSeen: daysAgo(0),
  },
  {
    id: "workload-007",
    name: "notification-service",
    type: "deployment",
    clusterId: "cluster-002",
    clusterName: "staging-eks-cluster",
    namespace: "staging",
    replicas: 2,
    readyReplicas: 2,
    images: ["gcr.io/vingroup/notification:v1.2.0"],
    labels: { app: "notification", tier: "backend" },
    status: "running",
    riskScore: 35,
    findingCount: 2,
    cpuRequest: "250m",
    cpuLimit: "500m",
    memoryRequest: "256Mi",
    memoryLimit: "512Mi",
    createdAt: daysAgo(90),
    lastSeen: daysAgo(0),
  },
  {
    id: "workload-008",
    name: "postgres-db",
    type: "statefulset",
    clusterId: "cluster-002",
    clusterName: "staging-eks-cluster",
    namespace: "staging",
    replicas: 1,
    readyReplicas: 1,
    images: ["postgres:15.4-alpine"],
    labels: { app: "postgres", tier: "database" },
    status: "running",
    riskScore: 45,
    findingCount: 2,
    cpuRequest: "500m",
    cpuLimit: "1000m",
    memoryRequest: "1Gi",
    memoryLimit: "2Gi",
    createdAt: daysAgo(120),
    lastSeen: daysAgo(0),
  },
];

// Container Images
export const containerImages: ContainerImage[] = [
  {
    id: "image-001",
    name: "nginx",
    tag: "1.25-alpine",
    fullName: "nginx:1.25-alpine",
    registry: "docker.io",
    digest: "sha256:a1b2c3d4e5f6...",
    size: 45,
    os: "linux",
    architecture: "amd64",
    workloadCount: 3,
    vulnerabilities: { critical: 0, high: 1, medium: 3, low: 5 },
    riskScore: 35,
    lastScanned: daysAgo(1),
    pushedAt: daysAgo(30),
    createdAt: daysAgo(180),
  },
  {
    id: "image-002",
    name: "vingroup/user-service",
    tag: "v2.5.1",
    fullName: "gcr.io/vingroup/user-service:v2.5.1",
    registry: "gcr.io",
    digest: "sha256:b2c3d4e5f6a7...",
    size: 250,
    os: "linux",
    architecture: "amd64",
    workloadCount: 5,
    vulnerabilities: { critical: 1, high: 3, medium: 8, low: 12 },
    riskScore: 72,
    lastScanned: daysAgo(0),
    pushedAt: daysAgo(7),
    createdAt: daysAgo(250),
  },
  {
    id: "image-003",
    name: "vingroup/payment-processor",
    tag: "v3.1.0",
    fullName: "gcr.io/vingroup/payment-processor:v3.1.0",
    registry: "gcr.io",
    digest: "sha256:c3d4e5f6a7b8...",
    size: 320,
    os: "linux",
    architecture: "amd64",
    workloadCount: 3,
    vulnerabilities: { critical: 2, high: 5, medium: 10, low: 8 },
    riskScore: 85,
    lastScanned: daysAgo(0),
    pushedAt: daysAgo(14),
    createdAt: daysAgo(300),
  },
  {
    id: "image-004",
    name: "redis",
    tag: "7.2-alpine",
    fullName: "redis:7.2-alpine",
    registry: "docker.io",
    digest: "sha256:d4e5f6a7b8c9...",
    size: 35,
    os: "linux",
    architecture: "amd64",
    workloadCount: 4,
    vulnerabilities: { critical: 0, high: 0, medium: 2, low: 3 },
    riskScore: 18,
    lastScanned: daysAgo(2),
    pushedAt: daysAgo(45),
    createdAt: daysAgo(200),
  },
  {
    id: "image-005",
    name: "fluent/fluent-bit",
    tag: "2.1.10",
    fullName: "fluent/fluent-bit:2.1.10",
    registry: "docker.io",
    digest: "sha256:e5f6a7b8c9d0...",
    size: 85,
    os: "linux",
    architecture: "amd64",
    workloadCount: 5,
    vulnerabilities: { critical: 0, high: 0, medium: 1, low: 2 },
    riskScore: 12,
    lastScanned: daysAgo(1),
    pushedAt: daysAgo(60),
    createdAt: daysAgo(100),
  },
  {
    id: "image-006",
    name: "postgres",
    tag: "15.4-alpine",
    fullName: "postgres:15.4-alpine",
    registry: "docker.io",
    digest: "sha256:f6a7b8c9d0e1...",
    size: 120,
    os: "linux",
    architecture: "amd64",
    workloadCount: 2,
    vulnerabilities: { critical: 0, high: 2, medium: 4, low: 6 },
    riskScore: 45,
    lastScanned: daysAgo(1),
    pushedAt: daysAgo(30),
    createdAt: daysAgo(120),
  },
  {
    id: "image-007",
    name: "vingroup/notification",
    tag: "v1.2.0",
    fullName: "gcr.io/vingroup/notification:v1.2.0",
    registry: "gcr.io",
    digest: "sha256:a7b8c9d0e1f2...",
    size: 180,
    os: "linux",
    architecture: "amd64",
    workloadCount: 2,
    vulnerabilities: { critical: 0, high: 1, medium: 5, low: 8 },
    riskScore: 38,
    lastScanned: daysAgo(0),
    pushedAt: daysAgo(21),
    createdAt: daysAgo(90),
  },
];

// ============================================
// Asset Findings
// ============================================

export const assetFindings: AssetFinding[] = [
  // API findings (added from apiFindings)
  ...apiFindings,
  // Domain findings
  {
    id: "finding-001",
    type: "misconfiguration",
    severity: "high",
    status: "open",
    title: "Missing DNSSEC configuration",
    description: "DNSSEC is not enabled for this domain, making it vulnerable to DNS spoofing attacks.",
    assetId: "dom-001",
    assetName: "vingroup.vn",
    assetType: "domain",
    rule: "DNS-001",
    remediation: "Enable DNSSEC at your domain registrar and configure DS records.",
    references: ["https://www.cloudflare.com/dns/dnssec/"],
    firstSeen: daysAgo(30),
    lastSeen: daysAgo(0),
  },
  {
    id: "finding-002",
    type: "misconfiguration",
    severity: "medium",
    status: "open",
    title: "SPF record too permissive",
    description: "The SPF record uses +all which allows any server to send emails on behalf of the domain.",
    assetId: "dom-001",
    assetName: "vingroup.vn",
    assetType: "domain",
    rule: "EMAIL-002",
    remediation: "Update SPF record to use -all or ~all to restrict email sending.",
    firstSeen: daysAgo(45),
    lastSeen: daysAgo(0),
  },
  // Website findings
  {
    id: "finding-003",
    type: "vulnerability",
    severity: "critical",
    status: "open",
    title: "SQL Injection vulnerability",
    description: "The login endpoint is vulnerable to SQL injection attacks via the username parameter.",
    assetId: "web-002",
    assetName: "ebanking.techcombank.com.vn",
    assetType: "website",
    cveId: "CVE-2024-1234",
    cvssScore: 9.8,
    cweId: "CWE-89",
    remediation: "Use parameterized queries instead of string concatenation for SQL queries.",
    references: ["https://owasp.org/www-community/attacks/SQL_Injection"],
    firstSeen: daysAgo(7),
    lastSeen: daysAgo(0),
  },
  {
    id: "finding-004",
    type: "misconfiguration",
    severity: "high",
    status: "in_progress",
    title: "Missing security headers",
    description: "The application is missing critical security headers: X-Frame-Options, Content-Security-Policy.",
    assetId: "web-002",
    assetName: "ebanking.techcombank.com.vn",
    assetType: "website",
    rule: "HEADER-001",
    remediation: "Add X-Frame-Options: DENY and implement a strict Content-Security-Policy.",
    firstSeen: daysAgo(60),
    lastSeen: daysAgo(0),
  },
  // Host findings
  {
    id: "finding-005",
    type: "vulnerability",
    severity: "critical",
    status: "open",
    title: "OpenSSH Remote Code Execution",
    description: "The installed OpenSSH version is vulnerable to remote code execution.",
    assetId: "host-001",
    assetName: "prod-web-01",
    assetType: "host",
    cveId: "CVE-2024-6387",
    cvssScore: 8.1,
    cweId: "CWE-362",
    remediation: "Upgrade OpenSSH to version 9.8 or later.",
    references: ["https://nvd.nist.gov/vuln/detail/CVE-2024-6387"],
    firstSeen: daysAgo(14),
    lastSeen: daysAgo(0),
  },
  {
    id: "finding-006",
    type: "misconfiguration",
    severity: "medium",
    status: "open",
    title: "Root login enabled via SSH",
    description: "SSH is configured to allow direct root login, increasing attack surface.",
    assetId: "host-001",
    assetName: "prod-web-01",
    assetType: "host",
    rule: "SSH-002",
    benchmark: "CIS Ubuntu 22.04",
    remediation: "Set PermitRootLogin to 'no' in /etc/ssh/sshd_config.",
    firstSeen: daysAgo(90),
    lastSeen: daysAgo(0),
  },
  // Container/K8s findings
  {
    id: "finding-007",
    type: "misconfiguration",
    severity: "high",
    status: "open",
    title: "Container running as root",
    description: "The container is running with root privileges, violating the principle of least privilege.",
    assetId: "container-003",
    assetName: "payment-processor",
    assetType: "container",
    rule: "K8S-SEC-001",
    benchmark: "CIS Kubernetes",
    remediation: "Set securityContext.runAsNonRoot: true in the pod spec.",
    firstSeen: daysAgo(30),
    lastSeen: daysAgo(0),
  },
  {
    id: "finding-008",
    type: "vulnerability",
    severity: "critical",
    status: "open",
    title: "Critical CVE in base image",
    description: "The container image contains a critical vulnerability in the OpenSSL library.",
    assetId: "container-003",
    assetName: "payment-processor",
    assetType: "container",
    cveId: "CVE-2024-0567",
    cvssScore: 9.1,
    cweId: "CWE-119",
    remediation: "Rebuild the image with an updated base image that patches OpenSSL.",
    firstSeen: daysAgo(5),
    lastSeen: daysAgo(0),
  },
  {
    id: "finding-009",
    type: "misconfiguration",
    severity: "medium",
    status: "open",
    title: "No resource limits defined",
    description: "The container has no CPU/memory limits, risking resource exhaustion.",
    assetId: "container-002",
    assetName: "user-service",
    assetType: "container",
    rule: "K8S-RES-001",
    remediation: "Define resources.limits in the container spec.",
    firstSeen: daysAgo(45),
    lastSeen: daysAgo(0),
  },
  // Database findings
  {
    id: "finding-010",
    type: "misconfiguration",
    severity: "critical",
    status: "open",
    title: "Database exposed to internet",
    description: "The database port 5432 is accessible from the public internet.",
    assetId: "db-001",
    assetName: "core-banking-db",
    assetType: "database",
    rule: "DB-NET-001",
    remediation: "Configure firewall rules to restrict database access to trusted IPs only.",
    firstSeen: daysAgo(3),
    lastSeen: daysAgo(0),
  },
  {
    id: "finding-011",
    type: "misconfiguration",
    severity: "high",
    status: "open",
    title: "Weak password policy",
    description: "Database password policy does not enforce complexity requirements.",
    assetId: "db-001",
    assetName: "core-banking-db",
    assetType: "database",
    rule: "DB-AUTH-002",
    benchmark: "CIS PostgreSQL",
    remediation: "Configure password_encryption and set minimum password length.",
    firstSeen: daysAgo(60),
    lastSeen: daysAgo(0),
  },
  // Mobile app findings
  {
    id: "finding-012",
    type: "vulnerability",
    severity: "high",
    status: "open",
    title: "Insecure data storage",
    description: "Sensitive data is stored in SharedPreferences without encryption.",
    assetId: "mobile-001",
    assetName: "VinBank Mobile",
    assetType: "mobile",
    cweId: "CWE-312",
    remediation: "Use EncryptedSharedPreferences or Android Keystore for sensitive data.",
    references: ["https://owasp.org/www-project-mobile-top-10/"],
    firstSeen: daysAgo(21),
    lastSeen: daysAgo(0),
  },
  {
    id: "finding-013",
    type: "misconfiguration",
    severity: "medium",
    status: "open",
    title: "Debug mode enabled in release build",
    description: "The application has debuggable flag set to true in the release APK.",
    assetId: "mobile-001",
    assetName: "VinBank Mobile",
    assetType: "mobile",
    rule: "MOBILE-001",
    remediation: "Set android:debuggable='false' in AndroidManifest.xml for release builds.",
    firstSeen: daysAgo(14),
    lastSeen: daysAgo(0),
  },
  // Repository findings
  {
    id: "finding-014",
    type: "secret",
    severity: "critical",
    status: "open",
    title: "AWS credentials in source code",
    description: "Hardcoded AWS access key found in configuration file.",
    assetId: "repo-003",
    assetName: "viettel/infrastructure-terraform",
    assetType: "repository",
    rule: "SECRET-001",
    remediation: "Remove the credentials and rotate the exposed keys immediately.",
    firstSeen: daysAgo(2),
    lastSeen: daysAgo(0),
  },
  {
    id: "finding-015",
    type: "vulnerability",
    severity: "high",
    status: "in_progress",
    title: "Vulnerable dependency: log4j",
    description: "The project uses log4j 2.14.0 which is vulnerable to Log4Shell.",
    assetId: "repo-001",
    assetName: "vingroup/core-banking-api",
    assetType: "repository",
    cveId: "CVE-2021-44228",
    cvssScore: 10.0,
    cweId: "CWE-502",
    remediation: "Upgrade log4j to version 2.17.1 or later.",
    firstSeen: daysAgo(30),
    lastSeen: daysAgo(0),
  },
  // Cloud findings
  {
    id: "finding-016",
    type: "misconfiguration",
    severity: "high",
    status: "open",
    title: "S3 bucket public access enabled",
    description: "The S3 bucket has public access enabled, exposing files to the internet.",
    assetId: "cloud-004",
    assetName: "aws-prod-s3-assets",
    assetType: "cloud",
    rule: "AWS-S3-001",
    benchmark: "CIS AWS",
    remediation: "Enable S3 Block Public Access settings at the bucket level.",
    firstSeen: daysAgo(7),
    lastSeen: daysAgo(0),
  },
  // Service findings
  {
    id: "finding-017",
    type: "misconfiguration",
    severity: "high",
    status: "open",
    title: "Redis without authentication",
    description: "Redis is accessible without password authentication.",
    assetId: "svc-003",
    assetName: "Redis - cache.internal.vn:6379",
    assetType: "service",
    rule: "REDIS-001",
    remediation: "Enable requirepass in redis.conf and use strong passwords.",
    firstSeen: daysAgo(45),
    lastSeen: daysAgo(0),
  },
];

// Get findings for a specific asset
export const getAssetFindings = (assetId: string): AssetFinding[] =>
  assetFindings.filter((f) => f.assetId === assetId);

// Get findings by severity
export const getFindingsBySeverity = (severity: AssetFinding["severity"]): AssetFinding[] =>
  assetFindings.filter((f) => f.severity === severity);

// Get K8s data
export const getK8sClusters = () => k8sClusters;
export const getK8sWorkloads = (clusterId?: string) =>
  clusterId ? k8sWorkloads.filter((w) => w.clusterId === clusterId) : k8sWorkloads;
export const getContainerImages = () => containerImages;

// Combine all assets
export const mockAssets: Asset[] = [
  ...domainAssets,
  ...websiteAssets,
  ...serviceAssets,
  ...repositoryAssets,
  ...cloudAssets,
  ...hostAssets,
  ...containerAssets,
  ...databaseAssets,
  ...mobileAssets,
  ...credentialAssets,
];

// Filter functions
export const getAssetsByType = (type: AssetType): Asset[] =>
  mockAssets.filter((asset) => asset.type === type);

export const getDomains = () => getAssetsByType("domain");
export const getWebsites = () => getAssetsByType("website");
export const getServices = () => getAssetsByType("service");
export const getRepositories = () => getAssetsByType("repository");
export const getCloudAssets = () => getAssetsByType("cloud");
export const getCredentials = () => getAssetsByType("credential");
export const getHosts = () => getAssetsByType("host");
export const getContainers = () => getAssetsByType("container");
export const getDatabases = () => getAssetsByType("database");
export const getMobileApps = () => getAssetsByType("mobile");

// API getters
export const getApis = () => apiAssets;
export const getApiEndpoints = (apiId?: string) =>
  apiId ? apiEndpoints.filter((e) => e.apiId === apiId) : apiEndpoints;
export const getApiById = (id: string) => apiAssets.find((a) => a.id === id);

// Stats
export const getAssetStats = () => ({
  total: mockAssets.length,
  domains: getDomains().length,
  websites: getWebsites().length,
  services: getServices().length,
  repositories: getRepositories().length,
  cloud: getCloudAssets().length,
  hosts: getHosts().length,
  containers: getContainers().length,
  databases: getDatabases().length,
  mobileApps: getMobileApps().length,
  credentials: getCredentials().length,
  apis: getApis().length,
  averageRiskScore: Math.round(
    mockAssets.reduce((acc, a) => acc + a.riskScore, 0) / mockAssets.length
  ),
  totalFindings: mockAssets.reduce((acc, a) => acc + a.findingCount, 0),
});
