/**
 * Asset Mock Data
 *
 * Vietnamese company mock data for development and testing
 */

import type { Asset, AssetType } from "../types";

// Helper to generate dates
const daysAgo = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

// Vietnamese domain assets
const domainAssets: Asset[] = [
  {
    id: "dom-001",
    type: "domain",
    name: "vingroup.vn",
    description: "Main corporate domain",
    status: "active",
    riskScore: 72,
    findingCount: 5,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      registrar: "VNNIC",
      expiryDate: "2026-05-15",
      nameservers: ["ns1.vingroup.vn", "ns2.vingroup.vn"],
    },
    tags: ["critical", "production"],
    firstSeen: daysAgo(365),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(365),
    updatedAt: daysAgo(1),
  },
  {
    id: "dom-002",
    type: "domain",
    name: "fpt.com.vn",
    description: "FPT Corporation main domain",
    status: "active",
    riskScore: 45,
    findingCount: 3,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      registrar: "VNNIC",
      expiryDate: "2025-12-20",
      nameservers: ["ns1.fpt.com.vn", "ns2.fpt.com.vn"],
    },
    tags: ["production"],
    firstSeen: daysAgo(300),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(300),
    updatedAt: daysAgo(2),
  },
  {
    id: "dom-003",
    type: "domain",
    name: "viettel.com.vn",
    description: "Viettel Group domain",
    status: "active",
    riskScore: 58,
    findingCount: 4,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      registrar: "VNNIC",
      expiryDate: "2026-08-10",
      nameservers: ["dns1.viettel.com.vn", "dns2.viettel.com.vn"],
    },
    tags: ["critical", "production"],
    firstSeen: daysAgo(400),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "dom-004",
    type: "domain",
    name: "techcombank.com.vn",
    description: "Techcombank domain",
    status: "active",
    riskScore: 82,
    findingCount: 7,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      registrar: "VNNIC",
      expiryDate: "2025-11-30",
      nameservers: ["ns1.techcombank.com.vn", "ns2.techcombank.com.vn"],
    },
    tags: ["critical", "banking", "production"],
    firstSeen: daysAgo(500),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(500),
    updatedAt: daysAgo(0),
  },
  {
    id: "dom-005",
    type: "domain",
    name: "vpbank.com.vn",
    description: "VPBank domain",
    status: "active",
    riskScore: 65,
    findingCount: 4,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      registrar: "VNNIC",
      expiryDate: "2026-03-15",
      nameservers: ["ns1.vpbank.com.vn", "ns2.vpbank.com.vn"],
    },
    tags: ["critical", "banking"],
    firstSeen: daysAgo(350),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(350),
    updatedAt: daysAgo(1),
  },
];

// Website assets
const websiteAssets: Asset[] = [
  {
    id: "web-001",
    type: "website",
    name: "portal.fpt.com.vn",
    description: "FPT Customer Portal",
    status: "active",
    riskScore: 45,
    findingCount: 3,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      technology: ["React", "Node.js", "PostgreSQL"],
      ssl: true,
      sslExpiry: "2025-06-15",
      httpStatus: 200,
    },
    tags: ["production", "customer-facing"],
    firstSeen: daysAgo(200),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(1),
  },
  {
    id: "web-002",
    type: "website",
    name: "ebanking.techcombank.com.vn",
    description: "Techcombank Internet Banking",
    status: "active",
    riskScore: 88,
    findingCount: 6,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      technology: ["Angular", "Java Spring", "Oracle"],
      ssl: true,
      sslExpiry: "2025-04-20",
      httpStatus: 200,
    },
    tags: ["critical", "banking", "customer-facing"],
    firstSeen: daysAgo(400),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(400),
    updatedAt: daysAgo(0),
  },
  {
    id: "web-003",
    type: "website",
    name: "shop.vinmart.vn",
    description: "VinMart E-commerce",
    status: "active",
    riskScore: 52,
    findingCount: 4,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      technology: ["Vue.js", "PHP Laravel", "MySQL"],
      ssl: true,
      sslExpiry: "2025-08-10",
      httpStatus: 200,
    },
    tags: ["production", "e-commerce"],
    firstSeen: daysAgo(180),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(2),
  },
  {
    id: "web-004",
    type: "website",
    name: "api.momo.vn",
    description: "MoMo API Gateway",
    status: "active",
    riskScore: 78,
    findingCount: 5,
    groupId: "grp-003",
    groupName: "Production - API Gateway",
    metadata: {
      technology: ["Go", "gRPC", "Redis"],
      ssl: true,
      sslExpiry: "2025-09-25",
      httpStatus: 200,
    },
    tags: ["critical", "api", "payment"],
    firstSeen: daysAgo(250),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(250),
    updatedAt: daysAgo(1),
  },
  {
    id: "web-005",
    type: "website",
    name: "admin.vnpt.vn",
    description: "VNPT Admin Portal",
    status: "active",
    riskScore: 35,
    findingCount: 2,
    groupId: "grp-007",
    groupName: "Internal Tools",
    metadata: {
      technology: ["React", "Python Django", "PostgreSQL"],
      ssl: true,
      sslExpiry: "2025-07-30",
      httpStatus: 200,
    },
    tags: ["internal", "admin"],
    firstSeen: daysAgo(150),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(150),
    updatedAt: daysAgo(3),
  },
];

// Service assets
const serviceAssets: Asset[] = [
  {
    id: "svc-001",
    type: "service",
    name: "SSH - 192.168.1.10:22",
    description: "Production SSH Server",
    status: "active",
    riskScore: 25,
    findingCount: 1,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      port: 22,
      protocol: "SSH",
      version: "OpenSSH 8.9",
      banner: "SSH-2.0-OpenSSH_8.9",
    },
    tags: ["production", "infrastructure"],
    firstSeen: daysAgo(400),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "svc-002",
    type: "service",
    name: "MySQL - db.internal.vn:3306",
    description: "Primary Database Server",
    status: "active",
    riskScore: 68,
    findingCount: 4,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      port: 3306,
      protocol: "MySQL",
      version: "MySQL 8.0.32",
    },
    tags: ["critical", "database"],
    firstSeen: daysAgo(450),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(450),
    updatedAt: daysAgo(0),
  },
  {
    id: "svc-003",
    type: "service",
    name: "Redis - cache.internal.vn:6379",
    description: "Redis Cache Cluster",
    status: "active",
    riskScore: 42,
    findingCount: 2,
    groupId: "grp-003",
    groupName: "Production - API Gateway",
    metadata: {
      port: 6379,
      protocol: "Redis",
      version: "Redis 7.0.11",
    },
    tags: ["production", "cache"],
    firstSeen: daysAgo(200),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(2),
  },
  {
    id: "svc-004",
    type: "service",
    name: "Kafka - kafka.internal.vn:9092",
    description: "Message Queue Cluster",
    status: "active",
    riskScore: 55,
    findingCount: 3,
    groupId: "grp-003",
    groupName: "Production - API Gateway",
    metadata: {
      port: 9092,
      protocol: "Kafka",
      version: "Apache Kafka 3.5.0",
    },
    tags: ["production", "messaging"],
    firstSeen: daysAgo(180),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(1),
  },
  {
    id: "svc-005",
    type: "service",
    name: "Elasticsearch - es.internal.vn:9200",
    description: "Log Search Cluster",
    status: "active",
    riskScore: 38,
    findingCount: 2,
    groupId: "grp-007",
    groupName: "Internal Tools",
    metadata: {
      port: 9200,
      protocol: "HTTP/Elasticsearch",
      version: "Elasticsearch 8.10.0",
    },
    tags: ["production", "logging"],
    firstSeen: daysAgo(150),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(150),
    updatedAt: daysAgo(3),
  },
];

// Repository assets
const repositoryAssets: Asset[] = [
  {
    id: "repo-001",
    type: "repository",
    name: "vingroup/core-banking-api",
    description: "Core Banking API Service",
    status: "active",
    riskScore: 62,
    findingCount: 4,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      provider: "github",
      visibility: "private",
      language: "Java",
      stars: 0,
    },
    tags: ["critical", "backend"],
    firstSeen: daysAgo(500),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(500),
    updatedAt: daysAgo(1),
  },
  {
    id: "repo-002",
    type: "repository",
    name: "fpt/ecommerce-frontend",
    description: "E-commerce Frontend Application",
    status: "active",
    riskScore: 35,
    findingCount: 2,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      provider: "gitlab",
      visibility: "private",
      language: "TypeScript",
      stars: 0,
    },
    tags: ["frontend", "production"],
    firstSeen: daysAgo(300),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(300),
    updatedAt: daysAgo(2),
  },
  {
    id: "repo-003",
    type: "repository",
    name: "viettel/infrastructure-terraform",
    description: "Infrastructure as Code",
    status: "active",
    riskScore: 78,
    findingCount: 6,
    groupId: "grp-006",
    groupName: "Cloud Infrastructure",
    metadata: {
      provider: "github",
      visibility: "private",
      language: "HCL",
      stars: 0,
    },
    tags: ["critical", "infrastructure"],
    firstSeen: daysAgo(250),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(250),
    updatedAt: daysAgo(0),
  },
  {
    id: "repo-004",
    type: "repository",
    name: "techcombank/mobile-app",
    description: "Mobile Banking Application",
    status: "active",
    riskScore: 85,
    findingCount: 7,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      provider: "bitbucket",
      visibility: "private",
      language: "Kotlin",
      stars: 0,
    },
    tags: ["critical", "mobile", "banking"],
    firstSeen: daysAgo(400),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "repo-005",
    type: "repository",
    name: "vpbank/docs-public",
    description: "Public Documentation",
    status: "active",
    riskScore: 15,
    findingCount: 1,
    groupId: "grp-005",
    groupName: "Partner Systems",
    metadata: {
      provider: "github",
      visibility: "public",
      language: "Markdown",
      stars: 12,
    },
    tags: ["documentation", "public"],
    firstSeen: daysAgo(100),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(100),
    updatedAt: daysAgo(5),
  },
];

// Cloud assets
const cloudAssets: Asset[] = [
  {
    id: "cloud-001",
    type: "cloud",
    name: "aws-prod-vpc-main",
    description: "Production VPC on AWS",
    status: "active",
    riskScore: 55,
    findingCount: 3,
    groupId: "grp-006",
    groupName: "Cloud Infrastructure",
    metadata: {
      cloudProvider: "aws",
      region: "ap-southeast-1",
      resourceType: "VPC",
    },
    tags: ["production", "network"],
    firstSeen: daysAgo(300),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(300),
    updatedAt: daysAgo(1),
  },
  {
    id: "cloud-002",
    type: "cloud",
    name: "gcp-prod-gke-cluster",
    description: "Production Kubernetes Cluster",
    status: "active",
    riskScore: 72,
    findingCount: 5,
    groupId: "grp-006",
    groupName: "Cloud Infrastructure",
    metadata: {
      cloudProvider: "gcp",
      region: "asia-southeast1",
      resourceType: "GKE Cluster",
    },
    tags: ["critical", "kubernetes"],
    firstSeen: daysAgo(250),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(250),
    updatedAt: daysAgo(0),
  },
  {
    id: "cloud-003",
    type: "cloud",
    name: "azure-prod-sql-server",
    description: "Azure SQL Database Server",
    status: "active",
    riskScore: 68,
    findingCount: 4,
    groupId: "grp-006",
    groupName: "Cloud Infrastructure",
    metadata: {
      cloudProvider: "azure",
      region: "Southeast Asia",
      resourceType: "SQL Server",
    },
    tags: ["critical", "database"],
    firstSeen: daysAgo(200),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(200),
    updatedAt: daysAgo(2),
  },
  {
    id: "cloud-004",
    type: "cloud",
    name: "aws-prod-s3-assets",
    description: "Production Assets Storage",
    status: "active",
    riskScore: 42,
    findingCount: 2,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      cloudProvider: "aws",
      region: "ap-southeast-1",
      resourceType: "S3 Bucket",
    },
    tags: ["production", "storage"],
    firstSeen: daysAgo(180),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(3),
  },
  {
    id: "cloud-005",
    type: "cloud",
    name: "aws-staging-ec2-fleet",
    description: "Staging EC2 Instances",
    status: "active",
    riskScore: 28,
    findingCount: 1,
    groupId: "grp-004",
    groupName: "Staging Environment",
    metadata: {
      cloudProvider: "aws",
      region: "ap-southeast-1",
      resourceType: "EC2",
    },
    tags: ["staging", "compute"],
    firstSeen: daysAgo(150),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(150),
    updatedAt: daysAgo(1),
  },
];

// Credential leak assets
const credentialAssets: Asset[] = [
  {
    id: "cred-001",
    type: "credential",
    name: "admin@vingroup.vn",
    description: "Leaked admin credentials",
    status: "active",
    riskScore: 95,
    findingCount: 1,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      source: "Data breach - DarkWeb",
      username: "admin@vingroup.vn",
      leakDate: "2024-08-15",
    },
    tags: ["critical", "credential-leak"],
    firstSeen: daysAgo(120),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(120),
    updatedAt: daysAgo(0),
  },
  {
    id: "cred-002",
    type: "credential",
    name: "developer@fpt.com.vn",
    description: "Developer account exposed",
    status: "active",
    riskScore: 75,
    findingCount: 1,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      source: "GitHub commit history",
      username: "developer@fpt.com.vn",
      leakDate: "2024-09-20",
    },
    tags: ["high", "credential-leak"],
    firstSeen: daysAgo(90),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(90),
    updatedAt: daysAgo(1),
  },
  {
    id: "cred-003",
    type: "credential",
    name: "api-key-techcombank",
    description: "API key leaked in public repo",
    status: "pending",
    riskScore: 88,
    findingCount: 1,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      source: "Public GitHub repository",
      username: "service-account",
      leakDate: "2024-10-05",
    },
    tags: ["critical", "api-key-leak"],
    firstSeen: daysAgo(60),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(60),
    updatedAt: daysAgo(2),
  },
  {
    id: "cred-004",
    type: "credential",
    name: "db-admin@vpbank.vn",
    description: "Database admin credentials",
    status: "completed",
    riskScore: 45,
    findingCount: 1,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      source: "Pastebin leak",
      username: "db-admin@vpbank.vn",
      leakDate: "2024-06-10",
    },
    tags: ["resolved", "credential-leak"],
    firstSeen: daysAgo(180),
    lastSeen: daysAgo(30),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(30),
  },
  {
    id: "cred-005",
    type: "credential",
    name: "ops@viettel.com.vn",
    description: "Operations team credentials",
    status: "active",
    riskScore: 65,
    findingCount: 1,
    groupId: "grp-006",
    groupName: "Cloud Infrastructure",
    metadata: {
      source: "Credential stuffing attack",
      username: "ops@viettel.com.vn",
      leakDate: "2024-11-01",
    },
    tags: ["high", "credential-leak"],
    firstSeen: daysAgo(45),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(45),
    updatedAt: daysAgo(1),
  },
];

// Combine all assets
export const mockAssets: Asset[] = [
  ...domainAssets,
  ...websiteAssets,
  ...serviceAssets,
  ...repositoryAssets,
  ...cloudAssets,
  ...credentialAssets,
];

// Filter functions
export const getAssetsByType = (type: AssetType): Asset[] =>
  mockAssets.filter((asset) => asset.type === type);

export const getDomains = () => getAssetsByType("domain");
export const getWebsites = () => getAssetsByType("website");
export const getServices = () => getAssetsByType("service");
export const getRepositories = () => getAssetsByType("repository");
export const getCloudAssets = () => getAssetsByType("cloud");
export const getCredentials = () => getAssetsByType("credential");

// Stats
export const getAssetStats = () => ({
  total: mockAssets.length,
  domains: getDomains().length,
  websites: getWebsites().length,
  services: getServices().length,
  repositories: getRepositories().length,
  cloud: getCloudAssets().length,
  credentials: getCredentials().length,
  averageRiskScore: Math.round(
    mockAssets.reduce((acc, a) => acc + a.riskScore, 0) / mockAssets.length
  ),
  totalFindings: mockAssets.reduce((acc, a) => acc + a.findingCount, 0),
});
