/**
 * Domain Assets Mock Data
 */

import type { BaseAsset } from "./helpers";
import { daysAgo } from "./helpers";

export const domainAssets: BaseAsset[] = [
  {
    id: "dom-001",
    type: "domain",
    name: "vingroup.vn",
    description: "Main corporate domain",
    status: "active",
    riskScore: 72,
    findingCount: 5,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      registrar: "VNNIC",
      expiryDate: "2026-05-15",
      nameservers: ["ns1.vingroup.vn", "ns2.vingroup.vn"],
    },
    tags: ["critical", "production"],
    firstSeen: daysAgo(365),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(365),
    updatedAt: daysAgo(1),
  },
  {
    id: "dom-002",
    type: "domain",
    name: "fpt.com.vn",
    description: "FPT Corporation main domain",
    status: "active",
    riskScore: 45,
    findingCount: 3,
    groupId: "grp-002",
    groupName: "Production - E-commerce",
    metadata: {
      registrar: "VNNIC",
      expiryDate: "2025-12-20",
      nameservers: ["ns1.fpt.com.vn", "ns2.fpt.com.vn"],
    },
    tags: ["production"],
    firstSeen: daysAgo(300),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(300),
    updatedAt: daysAgo(2),
  },
  {
    id: "dom-003",
    type: "domain",
    name: "viettel.com.vn",
    description: "Viettel Group domain",
    status: "active",
    riskScore: 58,
    findingCount: 4,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      registrar: "VNNIC",
      expiryDate: "2026-08-10",
      nameservers: ["dns1.viettel.com.vn", "dns2.viettel.com.vn"],
    },
    tags: ["critical", "production"],
    firstSeen: daysAgo(400),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(400),
    updatedAt: daysAgo(1),
  },
  {
    id: "dom-004",
    type: "domain",
    name: "techcombank.com.vn",
    description: "Techcombank domain",
    status: "active",
    riskScore: 82,
    findingCount: 7,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      registrar: "VNNIC",
      expiryDate: "2025-11-30",
      nameservers: ["ns1.techcombank.com.vn", "ns2.techcombank.com.vn"],
    },
    tags: ["critical", "banking", "production"],
    firstSeen: daysAgo(500),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(500),
    updatedAt: daysAgo(0),
  },
  {
    id: "dom-005",
    type: "domain",
    name: "vpbank.com.vn",
    description: "VPBank domain",
    status: "active",
    riskScore: 65,
    findingCount: 4,
    groupId: "grp-001",
    groupName: "Production - Core Banking",
    metadata: {
      registrar: "VNNIC",
      expiryDate: "2026-03-15",
      nameservers: ["ns1.vpbank.com.vn", "ns2.vpbank.com.vn"],
    },
    tags: ["critical", "banking"],
    firstSeen: daysAgo(350),
    lastSeen: daysAgo(0),
    createdAt: daysAgo(350),
    updatedAt: daysAgo(1),
  },
];
