/**
 * Asset Group Mock Data
 *
 * Vietnamese company asset groups for development and testing
 */

import type { AssetGroup } from "../types";

// Helper to generate dates
const daysAgo = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

export const mockAssetGroups: AssetGroup[] = [
  {
    id: "grp-001",
    name: "Production - Core Banking",
    description: "He thong ngan hang loi - Critical banking infrastructure",
    environment: "production",
    criticality: "critical",
    assetCount: 45,
    domainCount: 8,
    websiteCount: 12,
    serviceCount: 15,
    repositoryCount: 5,
    cloudCount: 3,
    credentialCount: 2,
    riskScore: 78,
    findingCount: 18,
    createdAt: daysAgo(365),
    updatedAt: daysAgo(1),
  },
  {
    id: "grp-002",
    name: "Production - E-commerce",
    description: "San thuong mai dien tu - E-commerce platforms",
    environment: "production",
    criticality: "high",
    assetCount: 67,
    domainCount: 12,
    websiteCount: 25,
    serviceCount: 18,
    repositoryCount: 8,
    cloudCount: 3,
    credentialCount: 1,
    riskScore: 65,
    findingCount: 12,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(2),
  },
  {
    id: "grp-003",
    name: "Production - API Gateway",
    description: "He thong API Gateway - API management systems",
    environment: "production",
    criticality: "critical",
    assetCount: 32,
    domainCount: 4,
    websiteCount: 8,
    serviceCount: 12,
    repositoryCount: 4,
    cloudCount: 3,
    credentialCount: 1,
    riskScore: 72,
    findingCount: 8,
    createdAt: daysAgo(250),
    updatedAt: daysAgo(1),
  },
  {
    id: "grp-004",
    name: "Staging Environment",
    description: "Moi truong staging - Pre-production testing",
    environment: "staging",
    criticality: "medium",
    assetCount: 45,
    domainCount: 6,
    websiteCount: 15,
    serviceCount: 14,
    repositoryCount: 6,
    cloudCount: 3,
    credentialCount: 1,
    riskScore: 42,
    findingCount: 5,
    createdAt: daysAgo(200),
    updatedAt: daysAgo(3),
  },
  {
    id: "grp-005",
    name: "Partner Systems",
    description: "He thong doi tac - Third-party integrations",
    environment: "production",
    criticality: "high",
    assetCount: 28,
    domainCount: 5,
    websiteCount: 8,
    serviceCount: 10,
    repositoryCount: 3,
    cloudCount: 1,
    credentialCount: 1,
    riskScore: 58,
    findingCount: 6,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(2),
  },
  {
    id: "grp-006",
    name: "Cloud Infrastructure",
    description: "Ha tang dam may - Cloud resources and services",
    environment: "production",
    criticality: "critical",
    assetCount: 35,
    domainCount: 2,
    websiteCount: 5,
    serviceCount: 8,
    repositoryCount: 5,
    cloudCount: 12,
    credentialCount: 3,
    riskScore: 68,
    findingCount: 9,
    createdAt: daysAgo(150),
    updatedAt: daysAgo(1),
  },
  {
    id: "grp-007",
    name: "Internal Tools",
    description: "Cong cu noi bo - Internal utilities and admin tools",
    environment: "production",
    criticality: "medium",
    assetCount: 25,
    domainCount: 3,
    websiteCount: 10,
    serviceCount: 8,
    repositoryCount: 3,
    cloudCount: 1,
    credentialCount: 0,
    riskScore: 35,
    findingCount: 3,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(4),
  },
  {
    id: "grp-008",
    name: "Development",
    description: "Moi truong phat trien - Development environments",
    environment: "development",
    criticality: "low",
    assetCount: 18,
    domainCount: 2,
    websiteCount: 6,
    serviceCount: 5,
    repositoryCount: 4,
    cloudCount: 1,
    credentialCount: 0,
    riskScore: 22,
    findingCount: 2,
    createdAt: daysAgo(100),
    updatedAt: daysAgo(5),
  },
  {
    id: "grp-009",
    name: "Legacy Systems",
    description: "He thong cu - Deprecated systems pending migration",
    environment: "production",
    criticality: "medium",
    assetCount: 8,
    domainCount: 3,
    websiteCount: 3,
    serviceCount: 2,
    repositoryCount: 0,
    cloudCount: 0,
    credentialCount: 0,
    riskScore: 82,
    findingCount: 7,
    createdAt: daysAgo(500),
    updatedAt: daysAgo(10),
  },
];

// Stats
export const getAssetGroupStats = () => ({
  total: mockAssetGroups.length,
  byEnvironment: {
    production: mockAssetGroups.filter((g) => g.environment === "production")
      .length,
    staging: mockAssetGroups.filter((g) => g.environment === "staging").length,
    development: mockAssetGroups.filter((g) => g.environment === "development")
      .length,
    testing: mockAssetGroups.filter((g) => g.environment === "testing").length,
  },
  byCriticality: {
    critical: mockAssetGroups.filter((g) => g.criticality === "critical")
      .length,
    high: mockAssetGroups.filter((g) => g.criticality === "high").length,
    medium: mockAssetGroups.filter((g) => g.criticality === "medium").length,
    low: mockAssetGroups.filter((g) => g.criticality === "low").length,
  },
  totalAssets: mockAssetGroups.reduce((acc, g) => acc + g.assetCount, 0),
  totalFindings: mockAssetGroups.reduce((acc, g) => acc + g.findingCount, 0),
  averageRiskScore: Math.round(
    mockAssetGroups.reduce((acc, g) => acc + g.riskScore, 0) /
      mockAssetGroups.length
  ),
});
