/**
 * Project Mock Data
 *
 * Comprehensive mock data for Git project management in CTEM platform
 */

import type {
  Project,
  SCMConnection,
  ImportJob,
  ImportPreview,
  ProjectStats,
  ProjectScan,
  Branch,
  SCMProvider,
  Criticality,
  FindingsSummary,
  ScanSettings,
} from '../types/project.types'

// ============================================
// Helper Functions
// ============================================

const daysAgo = (days: number): string => {
  const date = new Date()
  date.setDate(date.getDate() - days)
  return date.toISOString()
}

const hoursAgo = (hours: number): string => {
  const date = new Date()
  date.setHours(date.getHours() - hours)
  return date.toISOString()
}

// ============================================
// Mock SCM Connections
// ============================================

export const mockSCMConnections: SCMConnection[] = [
  {
    id: 'scm-001',
    tenant_id: 'tenant-001',
    name: 'GitHub Organization',
    provider: 'github',
    base_url: 'https://github.com',
    api_url: 'https://api.github.com',
    auth_type: 'oauth',
    scm_organization: 'acme-corp',
    status: 'connected',
    last_validated_at: hoursAgo(1),
    permissions: ['repo:read', 'repo:write', 'webhook:manage', 'org:read'],
    created_at: daysAgo(90),
    updated_at: hoursAgo(1),
    created_by: 'usr-001',
  },
  {
    id: 'scm-002',
    tenant_id: 'tenant-001',
    name: 'GitLab - Engineering Team',
    provider: 'gitlab',
    base_url: 'https://gitlab.acme.com',
    api_url: 'https://gitlab.acme.com/api/v4',
    auth_type: 'pat',
    scm_organization: 'engineering',
    status: 'connected',
    last_validated_at: daysAgo(1),
    permissions: ['repo:read', 'repo:write', 'webhook:manage'],
    created_at: daysAgo(60),
    updated_at: daysAgo(1),
    created_by: 'usr-001',
  },
  {
    id: 'scm-003',
    tenant_id: 'tenant-001',
    name: 'GitLab - Partner Portal',
    provider: 'gitlab',
    base_url: 'https://gitlab.partner.acme.com',
    api_url: 'https://gitlab.partner.acme.com/api/v4',
    auth_type: 'pat',
    scm_organization: 'partner-apps',
    status: 'connected',
    last_validated_at: hoursAgo(5),
    permissions: ['repo:read', 'repo:write'],
    created_at: daysAgo(45),
    updated_at: hoursAgo(5),
    created_by: 'usr-002',
  },
  {
    id: 'scm-004',
    tenant_id: 'tenant-001',
    name: 'Azure DevOps',
    provider: 'azure_devops',
    base_url: 'https://dev.azure.com/acme',
    auth_type: 'pat',
    scm_organization: 'acme',
    status: 'error',
    last_validated_at: daysAgo(3),
    error_message: 'Token expired. Please re-authenticate.',
    permissions: ['repo:read'],
    created_at: daysAgo(30),
    updated_at: daysAgo(3),
    created_by: 'usr-002',
  },
  {
    id: 'scm-005',
    tenant_id: 'tenant-001',
    name: 'Bitbucket - Vendor Projects',
    provider: 'bitbucket',
    base_url: 'https://bitbucket.org',
    api_url: 'https://api.bitbucket.org/2.0',
    auth_type: 'oauth',
    scm_organization: 'acme-vendors',
    status: 'connected',
    last_validated_at: daysAgo(2),
    permissions: ['repo:read', 'webhook:manage'],
    created_at: daysAgo(20),
    updated_at: daysAgo(2),
    created_by: 'usr-003',
  },
]

// ============================================
// Default Values
// ============================================

const _defaultFindingsSummary: FindingsSummary = {
  total: 0,
  by_severity: { critical: 0, high: 0, medium: 0, low: 0, info: 0 },
  by_status: {
    open: 0,
    confirmed: 0,
    in_progress: 0,
    resolved: 0,
    false_positive: 0,
    accepted_risk: 0,
  },
  by_type: { sast: 0, sca: 0, secret: 0, iac: 0, container: 0, dast: 0 },
}

const defaultScanSettings: ScanSettings = {
  enabled_scanners: ['sast', 'sca', 'secret'],
  auto_scan: true,
  scan_on_push: true,
  scan_on_pr: true,
  branch_patterns: ['main', 'release/*'],
  exclude_patterns: ['node_modules/**', 'vendor/**', 'dist/**'],
  scan_mode: 'incremental',
}

// ============================================
// Mock Projects
// ============================================

export const mockProjects: Project[] = [
  {
    id: 'proj-001',
    tenant_id: 'tenant-001',
    organization_id: 'org-001',
    name: 'acme-corp/api-gateway',
    description: 'Core API Gateway service for microservices architecture',
    scm_connection_id: 'scm-001',
    scm_provider: 'github',
    scm_organization: 'acme-corp',
    repo_id: 'gh-12345',
    repo_url: 'https://github.com/acme-corp/api-gateway.git',
    web_url: 'https://github.com/acme-corp/api-gateway',
    visibility: 'private',
    default_branch: 'main',
    protected_branches: ['main', 'release/*'],
    languages: { TypeScript: 72.5, Go: 22.3, Shell: 5.2 },
    primary_language: 'TypeScript',
    stars: 124,
    forks: 18,
    open_issues: 12,
    contributors_count: 8,
    size_kb: 45600,
    risk_score: 78,
    criticality: 'critical',
    scope: 'internal',
    exposure: 'public',
    findings_summary: {
      total: 23,
      by_severity: { critical: 2, high: 5, medium: 10, low: 4, info: 2 },
      by_status: {
        open: 15,
        confirmed: 3,
        in_progress: 2,
        resolved: 2,
        false_positive: 1,
        accepted_risk: 0,
      },
      by_type: { sast: 8, sca: 10, secret: 3, iac: 2, container: 0, dast: 0 },
      new_last_7_days: 5,
      resolved_last_7_days: 3,
      trend: 'increasing',
    },
    components_summary: {
      total: 156,
      direct: 45,
      transitive: 111,
      vulnerable: 12,
      outdated: 28,
      license_risk_high: 2,
      license_risk_medium: 5,
      unique_licenses: 18,
    },
    has_sbom: true,
    sbom_generated_at: hoursAgo(6),
    scan_settings: {
      enabled_scanners: ['sast', 'sca', 'secret', 'iac'],
      auto_scan: true,
      scan_on_push: true,
      scan_on_pr: true,
      branch_patterns: ['main', 'release/*', 'develop'],
      exclude_patterns: ['node_modules/**', 'dist/**', '*.test.ts'],
      scan_mode: 'incremental',
      fail_on_severity: ['critical', 'high'],
    },
    integrations: {
      jira: {
        enabled: true,
        project_key: 'SEC',
        issue_type: 'Bug',
        auto_create: true,
      },
      slack: {
        enabled: true,
        channel: '#security-alerts',
        notify_on: ['critical', 'high'],
      },
    },
    policy_id: 'policy-001',
    policy_name: 'Production Security Policy',
    compliance_status: 'non_compliant',
    quality_gate_status: 'failed',
    sync_status: 'synced',
    last_synced_at: hoursAgo(2),
    status: 'active',
    last_scanned_at: hoursAgo(6),
    last_scan_id: 'scan-proj-001-latest',
    security_features: {
      has_security_policy: true,
      branch_protection: true,
      secret_scanning_enabled: true,
      dependabot_enabled: true,
      code_scanning_enabled: true,
    },
    tags: ['production', 'critical', 'api'],
    owner_id: 'usr-001',
    team_ids: ['team-001', 'team-002'],
    group_id: 'grp-001',
    group_name: 'Core Services',
    created_at: daysAgo(365),
    updated_at: hoursAgo(2),
  },
  {
    id: 'proj-002',
    tenant_id: 'tenant-001',
    organization_id: 'org-001',
    name: 'acme-corp/user-service',
    description: 'User management and authentication service',
    scm_connection_id: 'scm-001',
    scm_provider: 'github',
    scm_organization: 'acme-corp',
    repo_id: 'gh-12346',
    repo_url: 'https://github.com/acme-corp/user-service.git',
    web_url: 'https://github.com/acme-corp/user-service',
    visibility: 'private',
    default_branch: 'main',
    protected_branches: ['main'],
    languages: { Java: 85.2, Kotlin: 10.5, Shell: 4.3 },
    primary_language: 'Java',
    stars: 67,
    forks: 5,
    open_issues: 8,
    contributors_count: 5,
    size_kb: 32000,
    risk_score: 65,
    criticality: 'high',
    scope: 'internal',
    exposure: 'restricted',
    findings_summary: {
      total: 15,
      by_severity: { critical: 1, high: 3, medium: 7, low: 3, info: 1 },
      by_status: {
        open: 10,
        confirmed: 2,
        in_progress: 1,
        resolved: 1,
        false_positive: 1,
        accepted_risk: 0,
      },
      by_type: { sast: 5, sca: 8, secret: 1, iac: 1, container: 0, dast: 0 },
      new_last_7_days: 2,
      resolved_last_7_days: 1,
      trend: 'stable',
    },
    components_summary: {
      total: 89,
      direct: 28,
      transitive: 61,
      vulnerable: 8,
      outdated: 15,
      license_risk_high: 1,
      license_risk_medium: 3,
      unique_licenses: 12,
    },
    has_sbom: true,
    sbom_generated_at: daysAgo(1),
    scan_settings: {
      ...defaultScanSettings,
      enabled_scanners: ['sast', 'sca', 'secret'],
    },
    compliance_status: 'partial',
    quality_gate_status: 'warning',
    sync_status: 'synced',
    last_synced_at: daysAgo(1),
    status: 'active',
    last_scanned_at: daysAgo(1),
    last_scan_id: 'scan-proj-002-latest',
    security_features: {
      has_security_policy: true,
      branch_protection: true,
      secret_scanning_enabled: true,
      dependabot_enabled: true,
      code_scanning_enabled: false,
    },
    tags: ['production', 'authentication'],
    owner_id: 'usr-002',
    team_ids: ['team-001'],
    group_id: 'grp-001',
    group_name: 'Core Services',
    created_at: daysAgo(280),
    updated_at: daysAgo(1),
  },
  {
    id: 'proj-003',
    tenant_id: 'tenant-001',
    organization_id: 'org-001',
    name: 'engineering/payment-processor',
    description: 'Payment processing microservice with PCI DSS compliance',
    scm_connection_id: 'scm-002',
    scm_provider: 'gitlab',
    scm_organization: 'engineering',
    repo_id: 'gl-789',
    repo_url: 'https://gitlab.acme.com/engineering/payment-processor.git',
    web_url: 'https://gitlab.acme.com/engineering/payment-processor',
    visibility: 'private',
    default_branch: 'main',
    protected_branches: ['main', 'release/*'],
    languages: { Go: 92.1, Shell: 5.2, Dockerfile: 2.7 },
    primary_language: 'Go',
    stars: 0,
    forks: 0,
    open_issues: 3,
    contributors_count: 4,
    size_kb: 18500,
    risk_score: 85,
    criticality: 'critical',
    scope: 'internal',
    exposure: 'private',
    findings_summary: {
      total: 8,
      by_severity: { critical: 0, high: 2, medium: 4, low: 1, info: 1 },
      by_status: {
        open: 5,
        confirmed: 1,
        in_progress: 1,
        resolved: 0,
        false_positive: 1,
        accepted_risk: 0,
      },
      by_type: { sast: 3, sca: 2, secret: 1, iac: 2, container: 0, dast: 0 },
      new_last_7_days: 1,
      resolved_last_7_days: 2,
      trend: 'decreasing',
    },
    components_summary: {
      total: 42,
      direct: 15,
      transitive: 27,
      vulnerable: 2,
      outdated: 5,
      license_risk_high: 0,
      license_risk_medium: 1,
      unique_licenses: 8,
    },
    has_sbom: true,
    sbom_generated_at: hoursAgo(12),
    scan_settings: {
      enabled_scanners: ['sast', 'sca', 'secret', 'iac', 'container'],
      auto_scan: true,
      scan_on_push: true,
      scan_on_pr: true,
      branch_patterns: ['main', 'release/*'],
      exclude_patterns: ['vendor/**'],
      scan_mode: 'full',
      fail_on_severity: ['critical', 'high'],
    },
    policy_id: 'policy-002',
    policy_name: 'PCI DSS Policy',
    compliance_status: 'compliant',
    quality_gate_status: 'passed',
    sync_status: 'synced',
    last_synced_at: hoursAgo(4),
    status: 'active',
    last_scanned_at: hoursAgo(12),
    last_scan_id: 'scan-proj-003-latest',
    security_features: {
      has_security_policy: true,
      branch_protection: true,
      secret_scanning_enabled: true,
      dependabot_enabled: false,
      code_scanning_enabled: true,
    },
    tags: ['production', 'pci-dss', 'payments', 'critical'],
    owner_id: 'usr-003',
    team_ids: ['team-003'],
    group_id: 'grp-002',
    group_name: 'Payment Systems',
    created_at: daysAgo(180),
    updated_at: hoursAgo(4),
  },
  {
    id: 'proj-004',
    tenant_id: 'tenant-001',
    organization_id: 'org-001',
    name: 'acme-corp/frontend-web',
    description: 'Main customer-facing web application',
    scm_connection_id: 'scm-001',
    scm_provider: 'github',
    scm_organization: 'acme-corp',
    repo_id: 'gh-12347',
    repo_url: 'https://github.com/acme-corp/frontend-web.git',
    web_url: 'https://github.com/acme-corp/frontend-web',
    visibility: 'public',
    default_branch: 'main',
    protected_branches: ['main'],
    languages: { TypeScript: 68.5, JavaScript: 18.2, CSS: 10.8, HTML: 2.5 },
    primary_language: 'TypeScript',
    stars: 1245,
    forks: 234,
    open_issues: 45,
    contributors_count: 25,
    size_kb: 125000,
    risk_score: 42,
    criticality: 'high',
    scope: 'external',
    exposure: 'public',
    findings_summary: {
      total: 12,
      by_severity: { critical: 0, high: 1, medium: 5, low: 4, info: 2 },
      by_status: {
        open: 6,
        confirmed: 2,
        in_progress: 2,
        resolved: 1,
        false_positive: 1,
        accepted_risk: 0,
      },
      by_type: { sast: 4, sca: 6, secret: 0, iac: 1, container: 1, dast: 0 },
      new_last_7_days: 0,
      resolved_last_7_days: 2,
      trend: 'decreasing',
    },
    components_summary: {
      total: 320,
      direct: 85,
      transitive: 235,
      vulnerable: 6,
      outdated: 42,
      license_risk_high: 0,
      license_risk_medium: 8,
      unique_licenses: 25,
    },
    has_sbom: true,
    sbom_generated_at: hoursAgo(3),
    scan_settings: defaultScanSettings,
    compliance_status: 'compliant',
    quality_gate_status: 'passed',
    sync_status: 'synced',
    last_synced_at: hoursAgo(1),
    status: 'active',
    last_scanned_at: hoursAgo(3),
    last_scan_id: 'scan-proj-004-latest',
    security_features: {
      has_security_policy: true,
      branch_protection: true,
      secret_scanning_enabled: true,
      dependabot_enabled: true,
      code_scanning_enabled: true,
    },
    tags: ['production', 'frontend', 'public'],
    owner_id: 'usr-004',
    team_ids: ['team-004'],
    group_id: 'grp-003',
    group_name: 'Web Applications',
    created_at: daysAgo(450),
    updated_at: hoursAgo(1),
  },
  {
    id: 'proj-005',
    tenant_id: 'tenant-001',
    organization_id: 'org-001',
    name: 'acme-corp/mobile-app',
    description: 'React Native mobile application',
    scm_connection_id: 'scm-001',
    scm_provider: 'github',
    scm_organization: 'acme-corp',
    repo_id: 'gh-12348',
    repo_url: 'https://github.com/acme-corp/mobile-app.git',
    web_url: 'https://github.com/acme-corp/mobile-app',
    visibility: 'private',
    default_branch: 'develop',
    protected_branches: ['main', 'develop'],
    languages: { TypeScript: 78.5, JavaScript: 15.2, Java: 3.8, Swift: 2.5 },
    primary_language: 'TypeScript',
    stars: 45,
    forks: 8,
    open_issues: 22,
    contributors_count: 12,
    size_kb: 85000,
    risk_score: 55,
    criticality: 'medium',
    scope: 'external',
    exposure: 'restricted',
    findings_summary: {
      total: 18,
      by_severity: { critical: 0, high: 2, medium: 8, low: 5, info: 3 },
      by_status: {
        open: 12,
        confirmed: 2,
        in_progress: 2,
        resolved: 1,
        false_positive: 1,
        accepted_risk: 0,
      },
      by_type: { sast: 6, sca: 10, secret: 1, iac: 0, container: 0, dast: 1 },
      new_last_7_days: 3,
      resolved_last_7_days: 1,
      trend: 'increasing',
    },
    has_sbom: false,
    scan_settings: {
      ...defaultScanSettings,
      enabled_scanners: ['sast', 'sca', 'secret'],
      branch_patterns: ['main', 'develop', 'release/*'],
    },
    compliance_status: 'not_assessed',
    quality_gate_status: 'warning',
    sync_status: 'synced',
    last_synced_at: hoursAgo(8),
    status: 'active',
    last_scanned_at: hoursAgo(8),
    last_scan_id: 'scan-proj-005-latest',
    security_features: {
      has_security_policy: false,
      branch_protection: true,
      secret_scanning_enabled: true,
      dependabot_enabled: true,
      code_scanning_enabled: false,
    },
    tags: ['mobile', 'react-native'],
    owner_id: 'usr-005',
    team_ids: ['team-005'],
    group_id: 'grp-004',
    group_name: 'Mobile Apps',
    created_at: daysAgo(200),
    updated_at: hoursAgo(8),
  },
  {
    id: 'proj-006',
    tenant_id: 'tenant-001',
    organization_id: 'org-001',
    name: 'acme-corp/data-pipeline',
    description: 'ETL data processing pipeline',
    scm_connection_id: 'scm-001',
    scm_provider: 'github',
    scm_organization: 'acme-corp',
    repo_id: 'gh-12349',
    repo_url: 'https://github.com/acme-corp/data-pipeline.git',
    web_url: 'https://github.com/acme-corp/data-pipeline',
    visibility: 'private',
    default_branch: 'main',
    protected_branches: ['main'],
    languages: { Python: 88.5, SQL: 8.2, Shell: 3.3 },
    primary_language: 'Python',
    stars: 12,
    forks: 2,
    open_issues: 5,
    contributors_count: 3,
    size_kb: 28000,
    risk_score: 35,
    criticality: 'medium',
    scope: 'internal',
    exposure: 'private',
    findings_summary: {
      total: 5,
      by_severity: { critical: 0, high: 0, medium: 2, low: 2, info: 1 },
      by_status: {
        open: 3,
        confirmed: 1,
        in_progress: 0,
        resolved: 1,
        false_positive: 0,
        accepted_risk: 0,
      },
      by_type: { sast: 2, sca: 2, secret: 0, iac: 1, container: 0, dast: 0 },
      new_last_7_days: 0,
      resolved_last_7_days: 1,
      trend: 'stable',
    },
    has_sbom: true,
    sbom_generated_at: daysAgo(2),
    scan_settings: {
      ...defaultScanSettings,
      enabled_scanners: ['sast', 'sca', 'iac'],
    },
    compliance_status: 'compliant',
    quality_gate_status: 'passed',
    sync_status: 'synced',
    last_synced_at: daysAgo(1),
    status: 'active',
    last_scanned_at: daysAgo(2),
    last_scan_id: 'scan-proj-006-latest',
    security_features: {
      has_security_policy: true,
      branch_protection: true,
      secret_scanning_enabled: true,
      dependabot_enabled: true,
      code_scanning_enabled: true,
    },
    tags: ['data', 'etl', 'python'],
    owner_id: 'usr-006',
    team_ids: ['team-006'],
    group_id: 'grp-005',
    group_name: 'Data Engineering',
    created_at: daysAgo(120),
    updated_at: daysAgo(1),
  },
  {
    id: 'proj-007',
    tenant_id: 'tenant-001',
    organization_id: 'org-001',
    name: 'acme-corp/legacy-monolith',
    description: 'Legacy monolithic application (migration in progress)',
    scm_connection_id: 'scm-001',
    scm_provider: 'github',
    scm_organization: 'acme-corp',
    repo_id: 'gh-12350',
    repo_url: 'https://github.com/acme-corp/legacy-monolith.git',
    web_url: 'https://github.com/acme-corp/legacy-monolith',
    visibility: 'private',
    default_branch: 'master',
    protected_branches: ['master'],
    languages: { PHP: 65.2, JavaScript: 22.5, CSS: 8.3, HTML: 4.0 },
    primary_language: 'PHP',
    stars: 5,
    forks: 0,
    open_issues: 128,
    contributors_count: 2,
    size_kb: 450000,
    risk_score: 92,
    criticality: 'high',
    scope: 'internal',
    exposure: 'restricted',
    findings_summary: {
      total: 156,
      by_severity: { critical: 8, high: 32, medium: 65, low: 35, info: 16 },
      by_status: {
        open: 120,
        confirmed: 15,
        in_progress: 8,
        resolved: 5,
        false_positive: 5,
        accepted_risk: 3,
      },
      by_type: { sast: 85, sca: 45, secret: 12, iac: 8, container: 6, dast: 0 },
      new_last_7_days: 0,
      resolved_last_7_days: 0,
      trend: 'stable',
    },
    has_sbom: false,
    scan_settings: {
      enabled_scanners: ['sast', 'sca'],
      auto_scan: false,
      scan_on_push: false,
      scan_on_pr: false,
      branch_patterns: ['master'],
      exclude_patterns: [],
      scan_mode: 'full',
    },
    compliance_status: 'non_compliant',
    quality_gate_status: 'failed',
    sync_status: 'synced',
    last_synced_at: daysAgo(7),
    status: 'inactive',
    last_scanned_at: daysAgo(30),
    last_scan_id: 'scan-proj-007-latest',
    security_features: {
      has_security_policy: false,
      branch_protection: false,
      secret_scanning_enabled: false,
      dependabot_enabled: false,
      code_scanning_enabled: false,
    },
    tags: ['legacy', 'migration', 'php'],
    owner_id: 'usr-001',
    team_ids: ['team-001'],
    group_id: 'grp-006',
    group_name: 'Legacy Systems',
    created_at: daysAgo(1825),
    updated_at: daysAgo(7),
  },
  {
    id: 'proj-008',
    tenant_id: 'tenant-001',
    organization_id: 'org-001',
    name: 'acme-corp/infra-terraform',
    description: 'Infrastructure as Code - Terraform configurations',
    scm_connection_id: 'scm-001',
    scm_provider: 'github',
    scm_organization: 'acme-corp',
    repo_id: 'gh-12351',
    repo_url: 'https://github.com/acme-corp/infra-terraform.git',
    web_url: 'https://github.com/acme-corp/infra-terraform',
    visibility: 'private',
    default_branch: 'main',
    protected_branches: ['main', 'production'],
    languages: { HCL: 92.5, Shell: 5.5, Python: 2.0 },
    primary_language: 'HCL',
    stars: 28,
    forks: 5,
    open_issues: 8,
    contributors_count: 6,
    size_kb: 12000,
    risk_score: 48,
    criticality: 'critical',
    scope: 'cloud',
    exposure: 'private',
    findings_summary: {
      total: 22,
      by_severity: { critical: 1, high: 4, medium: 10, low: 5, info: 2 },
      by_status: {
        open: 15,
        confirmed: 3,
        in_progress: 2,
        resolved: 1,
        false_positive: 1,
        accepted_risk: 0,
      },
      by_type: { sast: 0, sca: 0, secret: 2, iac: 18, container: 2, dast: 0 },
      new_last_7_days: 2,
      resolved_last_7_days: 3,
      trend: 'decreasing',
    },
    has_sbom: false,
    scan_settings: {
      enabled_scanners: ['iac', 'secret'],
      auto_scan: true,
      scan_on_push: true,
      scan_on_pr: true,
      branch_patterns: ['main', 'production'],
      exclude_patterns: ['.terraform/**'],
      scan_mode: 'full',
      fail_on_severity: ['critical'],
    },
    policy_id: 'policy-003',
    policy_name: 'Cloud Security Policy',
    compliance_status: 'partial',
    quality_gate_status: 'warning',
    sync_status: 'synced',
    last_synced_at: hoursAgo(5),
    status: 'active',
    last_scanned_at: hoursAgo(5),
    last_scan_id: 'scan-proj-008-latest',
    security_features: {
      has_security_policy: true,
      branch_protection: true,
      secret_scanning_enabled: true,
      dependabot_enabled: false,
      code_scanning_enabled: true,
    },
    tags: ['infrastructure', 'terraform', 'aws', 'critical'],
    owner_id: 'usr-007',
    team_ids: ['team-007'],
    group_id: 'grp-007',
    group_name: 'Infrastructure',
    created_at: daysAgo(300),
    updated_at: hoursAgo(5),
  },
  {
    id: 'proj-009',
    tenant_id: 'tenant-001',
    organization_id: 'org-001',
    name: 'acme-corp/docs-website',
    description: 'Public documentation website',
    scm_connection_id: 'scm-001',
    scm_provider: 'github',
    scm_organization: 'acme-corp',
    repo_id: 'gh-12352',
    repo_url: 'https://github.com/acme-corp/docs-website.git',
    web_url: 'https://github.com/acme-corp/docs-website',
    visibility: 'public',
    default_branch: 'main',
    protected_branches: ['main'],
    languages: { MDX: 75.5, TypeScript: 18.5, CSS: 6.0 },
    primary_language: 'MDX',
    stars: 89,
    forks: 45,
    open_issues: 12,
    contributors_count: 15,
    size_kb: 35000,
    risk_score: 15,
    criticality: 'low',
    scope: 'external',
    exposure: 'public',
    findings_summary: {
      total: 2,
      by_severity: { critical: 0, high: 0, medium: 1, low: 1, info: 0 },
      by_status: {
        open: 2,
        confirmed: 0,
        in_progress: 0,
        resolved: 0,
        false_positive: 0,
        accepted_risk: 0,
      },
      by_type: { sast: 0, sca: 2, secret: 0, iac: 0, container: 0, dast: 0 },
      new_last_7_days: 0,
      resolved_last_7_days: 0,
      trend: 'stable',
    },
    has_sbom: true,
    sbom_generated_at: daysAgo(3),
    scan_settings: {
      enabled_scanners: ['sca', 'secret'],
      auto_scan: true,
      scan_on_push: false,
      scan_on_pr: true,
      branch_patterns: ['main'],
      exclude_patterns: [],
      scan_mode: 'incremental',
    },
    compliance_status: 'compliant',
    quality_gate_status: 'passed',
    sync_status: 'synced',
    last_synced_at: daysAgo(1),
    status: 'active',
    last_scanned_at: daysAgo(3),
    last_scan_id: 'scan-proj-009-latest',
    security_features: {
      has_security_policy: true,
      branch_protection: true,
      secret_scanning_enabled: true,
      dependabot_enabled: true,
      code_scanning_enabled: false,
    },
    tags: ['docs', 'public', 'low-priority'],
    owner_id: 'usr-008',
    team_ids: ['team-008'],
    group_id: 'grp-008',
    group_name: 'Documentation',
    created_at: daysAgo(150),
    updated_at: daysAgo(1),
  },
  {
    id: 'proj-010',
    tenant_id: 'tenant-001',
    organization_id: 'org-001',
    name: 'acme-corp/internal-tools',
    description: 'Internal developer tools and utilities',
    scm_connection_id: 'scm-001',
    scm_provider: 'github',
    scm_organization: 'acme-corp',
    repo_id: 'gh-12353',
    repo_url: 'https://github.com/acme-corp/internal-tools.git',
    web_url: 'https://github.com/acme-corp/internal-tools',
    visibility: 'internal',
    default_branch: 'main',
    protected_branches: [],
    languages: { Python: 55.5, Shell: 30.2, Go: 14.3 },
    primary_language: 'Python',
    stars: 32,
    forks: 12,
    open_issues: 15,
    contributors_count: 8,
    size_kb: 18000,
    risk_score: 28,
    criticality: 'low',
    scope: 'internal',
    exposure: 'restricted',
    findings_summary: {
      total: 8,
      by_severity: { critical: 0, high: 0, medium: 3, low: 4, info: 1 },
      by_status: {
        open: 5,
        confirmed: 1,
        in_progress: 1,
        resolved: 1,
        false_positive: 0,
        accepted_risk: 0,
      },
      by_type: { sast: 3, sca: 4, secret: 1, iac: 0, container: 0, dast: 0 },
      new_last_7_days: 1,
      resolved_last_7_days: 0,
      trend: 'stable',
    },
    has_sbom: false,
    scan_settings: {
      enabled_scanners: ['sast', 'sca'],
      auto_scan: false,
      scan_on_push: false,
      scan_on_pr: false,
      branch_patterns: ['main'],
      exclude_patterns: [],
      scan_mode: 'incremental',
    },
    compliance_status: 'not_assessed',
    quality_gate_status: 'not_computed',
    sync_status: 'pending',
    status: 'active',
    last_scanned_at: daysAgo(14),
    last_scan_id: 'scan-proj-010-latest',
    security_features: {
      has_security_policy: false,
      branch_protection: false,
      secret_scanning_enabled: false,
      dependabot_enabled: true,
      code_scanning_enabled: false,
    },
    tags: ['internal', 'tools'],
    owner_id: 'usr-009',
    team_ids: ['team-001'],
    group_id: 'grp-009',
    group_name: 'Internal Tools',
    created_at: daysAgo(90),
    updated_at: daysAgo(7),
  },
  // Projects from GitLab Partner Portal (different GitLab instance)
  {
    id: 'proj-011',
    tenant_id: 'tenant-001',
    organization_id: 'org-001',
    name: 'partner-apps/merchant-portal',
    description: 'Partner merchant management portal',
    scm_connection_id: 'scm-003', // GitLab Partner Portal
    scm_provider: 'gitlab',
    scm_organization: 'partner-apps',
    repo_id: 'gl-partner-101',
    repo_url: 'https://gitlab.partner.acme.com/partner-apps/merchant-portal.git',
    web_url: 'https://gitlab.partner.acme.com/partner-apps/merchant-portal',
    visibility: 'private',
    default_branch: 'main',
    protected_branches: ['main', 'production'],
    languages: { TypeScript: 65.2, Vue: 28.5, CSS: 6.3 },
    primary_language: 'TypeScript',
    stars: 0,
    forks: 0,
    open_issues: 18,
    contributors_count: 6,
    size_kb: 52000,
    risk_score: 58,
    criticality: 'high',
    scope: 'partner',
    exposure: 'restricted',
    findings_summary: {
      total: 14,
      by_severity: { critical: 0, high: 3, medium: 6, low: 4, info: 1 },
      by_status: {
        open: 10,
        confirmed: 2,
        in_progress: 1,
        resolved: 1,
        false_positive: 0,
        accepted_risk: 0,
      },
      by_type: { sast: 5, sca: 7, secret: 1, iac: 1, container: 0, dast: 0 },
      new_last_7_days: 2,
      resolved_last_7_days: 1,
      trend: 'increasing',
    },
    has_sbom: true,
    sbom_generated_at: daysAgo(1),
    scan_settings: {
      ...defaultScanSettings,
      enabled_scanners: ['sast', 'sca', 'secret', 'iac'],
    },
    compliance_status: 'partial',
    quality_gate_status: 'warning',
    sync_status: 'synced',
    last_synced_at: hoursAgo(5),
    status: 'active',
    last_scanned_at: daysAgo(1),
    last_scan_id: 'scan-proj-011-latest',
    security_features: {
      has_security_policy: true,
      branch_protection: true,
      secret_scanning_enabled: false,
      dependabot_enabled: false,
      code_scanning_enabled: true,
    },
    tags: ['partner', 'portal', 'vue'],
    owner_id: 'usr-010',
    team_ids: ['team-009'],
    group_id: 'grp-010',
    group_name: 'Partner Systems',
    created_at: daysAgo(180),
    updated_at: hoursAgo(5),
  },
  {
    id: 'proj-012',
    tenant_id: 'tenant-001',
    organization_id: 'org-001',
    name: 'partner-apps/integration-sdk',
    description: 'SDK for third-party partner integrations',
    scm_connection_id: 'scm-003', // GitLab Partner Portal
    scm_provider: 'gitlab',
    scm_organization: 'partner-apps',
    repo_id: 'gl-partner-102',
    repo_url: 'https://gitlab.partner.acme.com/partner-apps/integration-sdk.git',
    web_url: 'https://gitlab.partner.acme.com/partner-apps/integration-sdk',
    visibility: 'private',
    default_branch: 'main',
    protected_branches: ['main'],
    languages: { TypeScript: 85.5, JavaScript: 12.3, Shell: 2.2 },
    primary_language: 'TypeScript',
    stars: 0,
    forks: 0,
    open_issues: 5,
    contributors_count: 3,
    size_kb: 15000,
    risk_score: 32,
    criticality: 'medium',
    scope: 'partner',
    exposure: 'restricted',
    findings_summary: {
      total: 4,
      by_severity: { critical: 0, high: 0, medium: 2, low: 2, info: 0 },
      by_status: {
        open: 2,
        confirmed: 1,
        in_progress: 0,
        resolved: 1,
        false_positive: 0,
        accepted_risk: 0,
      },
      by_type: { sast: 1, sca: 3, secret: 0, iac: 0, container: 0, dast: 0 },
      new_last_7_days: 0,
      resolved_last_7_days: 1,
      trend: 'decreasing',
    },
    has_sbom: true,
    sbom_generated_at: daysAgo(2),
    scan_settings: defaultScanSettings,
    compliance_status: 'compliant',
    quality_gate_status: 'passed',
    sync_status: 'synced',
    last_synced_at: daysAgo(1),
    status: 'active',
    last_scanned_at: daysAgo(2),
    last_scan_id: 'scan-proj-012-latest',
    security_features: {
      has_security_policy: true,
      branch_protection: true,
      secret_scanning_enabled: false,
      dependabot_enabled: false,
      code_scanning_enabled: true,
    },
    tags: ['partner', 'sdk', 'npm-package'],
    owner_id: 'usr-010',
    team_ids: ['team-009'],
    group_id: 'grp-010',
    group_name: 'Partner Systems',
    created_at: daysAgo(120),
    updated_at: daysAgo(1),
  },
  // Projects from Bitbucket (vendor projects)
  {
    id: 'proj-013',
    tenant_id: 'tenant-001',
    organization_id: 'org-001',
    name: 'acme-vendors/vendor-onboarding',
    description: 'Vendor onboarding and compliance system',
    scm_connection_id: 'scm-005', // Bitbucket
    scm_provider: 'bitbucket',
    scm_organization: 'acme-vendors',
    repo_id: 'bb-vendor-001',
    repo_url: 'https://bitbucket.org/acme-vendors/vendor-onboarding.git',
    web_url: 'https://bitbucket.org/acme-vendors/vendor-onboarding',
    visibility: 'private',
    default_branch: 'main',
    protected_branches: ['main'],
    languages: { Python: 72.5, JavaScript: 20.3, HTML: 7.2 },
    primary_language: 'Python',
    stars: 0,
    forks: 0,
    open_issues: 8,
    contributors_count: 4,
    size_kb: 32000,
    risk_score: 45,
    criticality: 'medium',
    scope: 'vendor',
    exposure: 'restricted',
    findings_summary: {
      total: 9,
      by_severity: { critical: 0, high: 1, medium: 4, low: 3, info: 1 },
      by_status: {
        open: 6,
        confirmed: 1,
        in_progress: 1,
        resolved: 1,
        false_positive: 0,
        accepted_risk: 0,
      },
      by_type: { sast: 4, sca: 4, secret: 0, iac: 1, container: 0, dast: 0 },
      new_last_7_days: 1,
      resolved_last_7_days: 0,
      trend: 'stable',
    },
    has_sbom: false,
    scan_settings: {
      enabled_scanners: ['sast', 'sca'],
      auto_scan: true,
      scan_on_push: true,
      scan_on_pr: true,
      branch_patterns: ['main'],
      exclude_patterns: [],
      scan_mode: 'incremental',
    },
    compliance_status: 'partial',
    quality_gate_status: 'warning',
    sync_status: 'synced',
    last_synced_at: daysAgo(2),
    status: 'active',
    last_scanned_at: daysAgo(3),
    last_scan_id: 'scan-proj-013-latest',
    security_features: {
      has_security_policy: false,
      branch_protection: true,
      secret_scanning_enabled: false,
      dependabot_enabled: false,
      code_scanning_enabled: false,
    },
    tags: ['vendor', 'compliance', 'python'],
    owner_id: 'usr-011',
    team_ids: ['team-010'],
    group_id: 'grp-011',
    group_name: 'Vendor Management',
    created_at: daysAgo(100),
    updated_at: daysAgo(2),
  },
]

// ============================================
// Mock Project Scans
// ============================================

export const mockProjectScans: ProjectScan[] = [
  {
    id: 'scan-001',
    project_id: 'proj-001',
    branch: 'main',
    commit_sha: 'abc123def456',
    commit_message: 'feat: add new API endpoint for user preferences',
    trigger: 'push',
    scan_mode: 'incremental',
    scanners: ['sast', 'sca', 'secret'],
    status: 'completed',
    progress: 100,
    findings_new: 2,
    findings_fixed: 1,
    findings_total: 23,
    quality_gate_passed: false,
    queued_at: hoursAgo(7),
    started_at: hoursAgo(7),
    completed_at: hoursAgo(6),
    duration_seconds: 342,
  },
  {
    id: 'scan-002',
    project_id: 'proj-001',
    branch: 'feature/oauth-integration',
    commit_sha: 'xyz789abc012',
    commit_message: 'feat: integrate OAuth2 provider',
    trigger: 'pr',
    scan_mode: 'diff',
    scanners: ['sast', 'sca', 'secret'],
    status: 'running',
    progress: 65,
    findings_new: 1,
    findings_fixed: 0,
    findings_total: 24,
    queued_at: hoursAgo(1),
    started_at: hoursAgo(1),
  },
  {
    id: 'scan-003',
    project_id: 'proj-003',
    branch: 'main',
    commit_sha: 'def456ghi789',
    commit_message: 'fix: resolve payment validation issue',
    trigger: 'push',
    scan_mode: 'full',
    scanners: ['sast', 'sca', 'secret', 'iac', 'container'],
    status: 'completed',
    progress: 100,
    findings_new: 0,
    findings_fixed: 2,
    findings_total: 8,
    quality_gate_passed: true,
    queued_at: hoursAgo(13),
    started_at: hoursAgo(13),
    completed_at: hoursAgo(12),
    duration_seconds: 1250,
  },
]

// ============================================
// Mock Branches
// ============================================

export const mockBranches: Branch[] = [
  {
    name: 'main',
    project_id: 'proj-001',
    is_default: true,
    is_protected: true,
    scan_on_push: true,
    scan_on_pr: true,
    last_commit_sha: 'abc123def456',
    last_commit_message: 'feat: add new API endpoint for user preferences',
    last_commit_author: 'John Doe',
    last_commit_at: hoursAgo(6),
    last_scan_id: 'scan-001',
    last_scanned_at: hoursAgo(6),
    findings_count: 23,
    keep_when_inactive: true,
  },
  {
    name: 'develop',
    project_id: 'proj-001',
    is_default: false,
    is_protected: true,
    scan_on_push: true,
    scan_on_pr: true,
    last_commit_sha: 'ghi789jkl012',
    last_commit_message: 'merge: feature/auth into develop',
    last_commit_author: 'Jane Smith',
    last_commit_at: hoursAgo(2),
    findings_count: 25,
    keep_when_inactive: true,
  },
  {
    name: 'feature/oauth-integration',
    project_id: 'proj-001',
    is_default: false,
    is_protected: false,
    scan_on_push: false,
    scan_on_pr: true,
    last_commit_sha: 'xyz789abc012',
    last_commit_message: 'feat: integrate OAuth2 provider',
    last_commit_author: 'John Doe',
    last_commit_at: hoursAgo(1),
    last_scan_id: 'scan-002',
    last_scanned_at: hoursAgo(1),
    findings_count: 24,
    keep_when_inactive: false,
    retention_days: 30,
  },
]

// ============================================
// Mock Import Preview
// ============================================

export const mockImportPreview: ImportPreview = {
  total_found: 25,
  will_import: 18,
  already_imported: 5,
  excluded: 2,
  repositories: [
    {
      repo_id: 'gh-99001',
      full_name: 'acme-corp/new-service',
      name: 'new-service',
      visibility: 'private',
      default_branch: 'main',
      language: 'TypeScript',
      stars: 5,
      updated_at: daysAgo(2),
      status: 'new',
    },
    {
      repo_id: 'gh-99002',
      full_name: 'acme-corp/analytics-dashboard',
      name: 'analytics-dashboard',
      visibility: 'private',
      default_branch: 'main',
      language: 'TypeScript',
      stars: 12,
      updated_at: daysAgo(1),
      status: 'new',
    },
    {
      repo_id: 'gh-99003',
      full_name: 'acme-corp/api-gateway',
      name: 'api-gateway',
      visibility: 'private',
      default_branch: 'main',
      language: 'TypeScript',
      stars: 124,
      updated_at: hoursAgo(2),
      status: 'exists',
    },
    {
      repo_id: 'gh-99004',
      full_name: 'acme-corp/archived-project',
      name: 'archived-project',
      visibility: 'private',
      default_branch: 'master',
      language: 'JavaScript',
      stars: 0,
      updated_at: daysAgo(365),
      status: 'excluded',
      exclude_reason: 'Repository is archived',
    },
  ],
}

// ============================================
// Mock Import Job
// ============================================

export const mockImportJob: ImportJob = {
  id: 'import-001',
  tenant_id: 'tenant-001',
  scm_connection_id: 'scm-001',
  status: 'completed',
  progress: 100,
  total_repos: 18,
  imported_count: 17,
  failed_count: 1,
  skipped_count: 0,
  errors: [
    {
      repo_name: 'acme-corp/private-fork',
      error: 'Insufficient permissions to access repository',
    },
  ],
  started_at: hoursAgo(2),
  completed_at: hoursAgo(1),
  created_at: hoursAgo(2),
}

// ============================================
// Stats Functions
// ============================================

export const getProjectStats = (): ProjectStats => {
  const projects = mockProjects

  return {
    total: projects.length,

    by_provider: {
      github: projects.filter((p) => p.scm_provider === 'github').length,
      gitlab: projects.filter((p) => p.scm_provider === 'gitlab').length,
      bitbucket: projects.filter((p) => p.scm_provider === 'bitbucket').length,
      azure_devops: projects.filter((p) => p.scm_provider === 'azure_devops').length,
      codecommit: projects.filter((p) => p.scm_provider === 'codecommit').length,
      local: projects.filter((p) => p.scm_provider === 'local').length,
    },

    by_status: {
      active: projects.filter((p) => p.status === 'active').length,
      archived: projects.filter((p) => p.status === 'archived').length,
      inactive: projects.filter((p) => p.status === 'inactive').length,
      importing: projects.filter((p) => p.status === 'importing').length,
    },

    by_visibility: {
      public: projects.filter((p) => p.visibility === 'public').length,
      private: projects.filter((p) => p.visibility === 'private').length,
      internal: projects.filter((p) => p.visibility === 'internal').length,
    },

    by_criticality: {
      critical: projects.filter((p) => p.criticality === 'critical').length,
      high: projects.filter((p) => p.criticality === 'high').length,
      medium: projects.filter((p) => p.criticality === 'medium').length,
      low: projects.filter((p) => p.criticality === 'low').length,
    },

    by_compliance: {
      compliant: projects.filter((p) => p.compliance_status === 'compliant').length,
      non_compliant: projects.filter((p) => p.compliance_status === 'non_compliant').length,
      not_assessed: projects.filter((p) => p.compliance_status === 'not_assessed').length,
      partial: projects.filter((p) => p.compliance_status === 'partial').length,
    },

    by_quality_gate: {
      passed: projects.filter((p) => p.quality_gate_status === 'passed').length,
      failed: projects.filter((p) => p.quality_gate_status === 'failed').length,
      warning: projects.filter((p) => p.quality_gate_status === 'warning').length,
      not_computed: projects.filter((p) => p.quality_gate_status === 'not_computed').length,
    },

    with_findings: projects.filter((p) => p.findings_summary.total > 0).length,
    with_critical_findings: projects.filter(
      (p) => p.findings_summary.by_severity.critical > 0
    ).length,
    avg_risk_score: Math.round(
      projects.reduce((acc, p) => acc + p.risk_score, 0) / projects.length
    ),
    total_findings: projects.reduce((acc, p) => acc + p.findings_summary.total, 0),

    total_components: projects.reduce(
      (acc, p) => acc + (p.components_summary?.total || 0),
      0
    ),
    vulnerable_components: projects.reduce(
      (acc, p) => acc + (p.components_summary?.vulnerable || 0),
      0
    ),

    synced: projects.filter((p) => p.sync_status === 'synced').length,
    sync_errors: projects.filter((p) => p.sync_status === 'error').length,

    scanned_last_24h: projects.filter((p) => {
      if (!p.last_scanned_at) return false
      const scannedAt = new Date(p.last_scanned_at)
      const oneDayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000)
      return scannedAt > oneDayAgo
    }).length,
    scanned_last_7d: projects.filter((p) => {
      if (!p.last_scanned_at) return false
      const scannedAt = new Date(p.last_scanned_at)
      const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)
      return scannedAt > sevenDaysAgo
    }).length,
    never_scanned: projects.filter((p) => !p.last_scanned_at).length,
  }
}

// ============================================
// Utility Functions
// ============================================

export const getProjectById = (id: string): Project | undefined => {
  return mockProjects.find((p) => p.id === id)
}

export const getProjectsByProvider = (provider: SCMProvider): Project[] => {
  return mockProjects.filter((p) => p.scm_provider === provider)
}

export const getProjectsByCriticality = (criticality: Criticality): Project[] => {
  return mockProjects.filter((p) => p.criticality === criticality)
}

export const getCriticalProjects = (): Project[] => {
  return mockProjects.filter(
    (p) =>
      p.criticality === 'critical' ||
      p.findings_summary.by_severity.critical > 0 ||
      p.risk_score >= 80
  )
}

export const getProjectsWithFindings = (): Project[] => {
  return mockProjects.filter((p) => p.findings_summary.total > 0)
}

export const getSCMConnectionById = (id: string): SCMConnection | undefined => {
  return mockSCMConnections.find((c) => c.id === id)
}

export const getActiveSCMConnections = (): SCMConnection[] => {
  return mockSCMConnections.filter((c) => c.status === 'connected')
}
