/**
 * Project Detail Mock Data
 *
 * Mock data for branches, findings, activities for the project detail page
 */

import type {
  BranchDetail,
  FindingDetail,
  ActivityLog,
  SLAPolicy,
  FindingsSummary,
} from '../types/project.types'

// ============================================
// Helper Functions
// ============================================

const hoursAgo = (hours: number): string => {
  const date = new Date()
  date.setHours(date.getHours() - hours)
  return date.toISOString()
}

const daysAgo = (days: number): string => {
  const date = new Date()
  date.setDate(date.getDate() - days)
  return date.toISOString()
}

const daysFromNow = (days: number): string => {
  const date = new Date()
  date.setDate(date.getDate() + days)
  return date.toISOString()
}

// ============================================
// Mock Branches for proj-001 (api-gateway)
// ============================================

export const mockBranches: BranchDetail[] = [
  {
    id: 'branch-001',
    project_id: 'proj-001',
    name: 'main',
    type: 'main',
    is_default: true,
    is_protected: true,
    last_commit_sha: 'a1b2c3d4e5f6',
    last_commit_message: 'fix: resolve authentication race condition',
    last_commit_author: 'Jane Doe',
    last_commit_author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jane',
    last_commit_at: hoursAgo(2),
    last_scan_id: 'scan-101',
    last_scanned_at: hoursAgo(2),
    scan_status: 'passed',
    quality_gate_status: 'passed',
    findings_summary: {
      total: 46,
      by_severity: { critical: 2, high: 7, medium: 14, low: 18, info: 5 },
      by_status: { open: 23, confirmed: 8, in_progress: 6, resolved: 5, false_positive: 2, accepted_risk: 2 },
      by_type: { sast: 18, sca: 15, secret: 5, iac: 4, container: 3, dast: 1 },
      new_last_7_days: 3,
      resolved_last_7_days: 5,
      trend: 'decreasing',
    },
    scan_on_push: true,
    scan_on_pr: true,
    created_at: daysAgo(180),
    updated_at: hoursAgo(2),
  },
  {
    id: 'branch-002',
    project_id: 'proj-001',
    name: 'develop',
    type: 'develop',
    is_default: false,
    is_protected: true,
    last_commit_sha: 'b2c3d4e5f6g7',
    last_commit_message: 'feat: add rate limiting middleware',
    last_commit_author: 'John Smith',
    last_commit_author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=john',
    last_commit_at: hoursAgo(4),
    last_scan_id: 'scan-102',
    last_scanned_at: hoursAgo(4),
    scan_status: 'warning',
    quality_gate_status: 'warning',
    findings_summary: {
      total: 52,
      by_severity: { critical: 3, high: 9, medium: 16, low: 19, info: 5 },
      by_status: { open: 28, confirmed: 10, in_progress: 5, resolved: 5, false_positive: 2, accepted_risk: 2 },
      by_type: { sast: 20, sca: 17, secret: 6, iac: 5, container: 3, dast: 1 },
      new_last_7_days: 8,
      resolved_last_7_days: 2,
      trend: 'increasing',
    },
    compared_to_default: {
      new_findings: 6,
      resolved_findings: 0,
      unchanged_findings: 46,
    },
    scan_on_push: true,
    scan_on_pr: true,
    created_at: daysAgo(180),
    updated_at: hoursAgo(4),
  },
  {
    id: 'branch-003',
    project_id: 'proj-001',
    name: 'feature/auth-v2',
    type: 'feature',
    is_default: false,
    is_protected: false,
    last_commit_sha: 'c3d4e5f6g7h8',
    last_commit_message: 'feat: implement OAuth2 PKCE flow',
    last_commit_author: 'Alice Chen',
    last_commit_author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alice',
    last_commit_at: daysAgo(1),
    last_scan_id: 'scan-103',
    last_scanned_at: daysAgo(1),
    scan_status: 'passed',
    quality_gate_status: 'passed',
    findings_summary: {
      total: 48,
      by_severity: { critical: 2, high: 8, medium: 15, low: 18, info: 5 },
      by_status: { open: 25, confirmed: 8, in_progress: 6, resolved: 5, false_positive: 2, accepted_risk: 2 },
      by_type: { sast: 19, sca: 16, secret: 5, iac: 4, container: 3, dast: 1 },
    },
    compared_to_default: {
      new_findings: 2,
      resolved_findings: 0,
      unchanged_findings: 46,
    },
    scan_on_push: true,
    scan_on_pr: true,
    created_at: daysAgo(14),
    updated_at: daysAgo(1),
  },
  {
    id: 'branch-004',
    project_id: 'proj-001',
    name: 'release/v2.0',
    type: 'release',
    is_default: false,
    is_protected: true,
    last_commit_sha: 'd4e5f6g7h8i9',
    last_commit_message: 'chore: bump version to 2.0.0-rc1',
    last_commit_author: 'Bob Wilson',
    last_commit_author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bob',
    last_commit_at: hoursAgo(30),
    last_scan_id: 'scan-104',
    last_scanned_at: hoursAgo(30),
    scan_status: 'failed',
    quality_gate_status: 'failed',
    findings_summary: {
      total: 49,
      by_severity: { critical: 4, high: 10, medium: 14, low: 16, info: 5 },
      by_status: { open: 27, confirmed: 9, in_progress: 4, resolved: 5, false_positive: 2, accepted_risk: 2 },
      by_type: { sast: 19, sca: 17, secret: 5, iac: 4, container: 3, dast: 1 },
    },
    compared_to_default: {
      new_findings: 3,
      resolved_findings: 0,
      unchanged_findings: 46,
    },
    scan_on_push: true,
    scan_on_pr: true,
    created_at: daysAgo(7),
    updated_at: hoursAgo(30),
  },
  {
    id: 'branch-005',
    project_id: 'proj-001',
    name: 'hotfix/login-bypass',
    type: 'hotfix',
    is_default: false,
    is_protected: false,
    last_commit_sha: 'e5f6g7h8i9j0',
    last_commit_message: 'fix: patch login bypass vulnerability',
    last_commit_author: 'Jane Doe',
    last_commit_author_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jane',
    last_commit_at: hoursAgo(6),
    last_scan_id: 'scan-105',
    last_scanned_at: hoursAgo(6),
    scan_status: 'passed',
    quality_gate_status: 'passed',
    findings_summary: {
      total: 44,
      by_severity: { critical: 1, high: 6, medium: 14, low: 18, info: 5 },
      by_status: { open: 21, confirmed: 8, in_progress: 6, resolved: 5, false_positive: 2, accepted_risk: 2 },
      by_type: { sast: 17, sca: 15, secret: 4, iac: 4, container: 3, dast: 1 },
    },
    compared_to_default: {
      new_findings: 0,
      resolved_findings: 2,
      unchanged_findings: 44,
    },
    scan_on_push: true,
    scan_on_pr: true,
    created_at: daysAgo(2),
    updated_at: hoursAgo(6),
  },
]

// ============================================
// Mock Findings for proj-001
// ============================================

export const mockFindings: FindingDetail[] = [
  {
    id: 'SEC-001',
    project_id: 'proj-001',
    title: 'SQL Injection in User Login',
    description: 'User-controlled input is directly concatenated into SQL query without proper sanitization, allowing potential SQL injection attacks.',
    recommendation: 'Use parameterized queries or prepared statements instead of string concatenation.',
    file_path: 'src/auth/login.ts',
    line_start: 145,
    line_end: 152,
    code_snippet: `const query = \`SELECT * FROM users WHERE email = '\${email}' AND password = '\${password}'\`;
const result = await db.query(query);`,
    scanner_type: 'sast',
    rule_id: 'sql-injection-001',
    rule_name: 'SQL Injection Prevention',
    severity: 'critical',
    cvss_score: 9.8,
    cwe_ids: ['CWE-89'],
    owasp_ids: ['A03:2021'],
    status: 'open',
    triage_status: 'confirmed',
    triaged_by: 'usr-001',
    triaged_at: daysAgo(3),
    assigned_to: 'usr-001',
    assigned_to_name: 'Jane Doe',
    assigned_to_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jane',
    assigned_at: daysAgo(2),
    sla_deadline: daysFromNow(-1),
    sla_status: 'overdue',
    sla_days_remaining: -1,
    branches: ['main', 'develop', 'release/v2.0'],
    first_detected_branch: 'main',
    first_detected_commit: 'abc123',
    first_detected_at: daysAgo(10),
    last_seen_branch: 'main',
    last_seen_commit: 'a1b2c3d4e5f6',
    last_seen_at: hoursAgo(2),
    duplicate_count: 0,
    comments_count: 3,
    related_issue_url: 'https://jira.example.com/SEC-1234',
    created_at: daysAgo(10),
    updated_at: daysAgo(1),
  },
  {
    id: 'SEC-002',
    project_id: 'proj-001',
    title: 'Hardcoded AWS Secret Key',
    description: 'AWS secret access key found hardcoded in configuration file. This could lead to unauthorized access to AWS resources.',
    recommendation: 'Remove the hardcoded secret and use environment variables or AWS Secrets Manager.',
    file_path: 'src/config/aws.config.ts',
    line_start: 23,
    line_end: 23,
    code_snippet: `const AWS_SECRET_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY";`,
    scanner_type: 'secret',
    rule_id: 'aws-secret-001',
    rule_name: 'AWS Secret Detection',
    severity: 'critical',
    cvss_score: 9.1,
    cwe_ids: ['CWE-798'],
    owasp_ids: ['A07:2021'],
    status: 'in_progress',
    triage_status: 'confirmed',
    triaged_by: 'usr-002',
    triaged_at: daysAgo(2),
    assigned_to: 'usr-002',
    assigned_to_name: 'John Smith',
    assigned_to_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=john',
    assigned_at: daysAgo(1),
    sla_deadline: daysFromNow(1),
    sla_status: 'warning',
    sla_days_remaining: 1,
    branches: ['main', 'develop'],
    first_detected_branch: 'develop',
    first_detected_commit: 'def456',
    first_detected_at: daysAgo(5),
    last_seen_branch: 'main',
    last_seen_commit: 'a1b2c3d4e5f6',
    last_seen_at: hoursAgo(2),
    duplicate_count: 0,
    comments_count: 2,
    created_at: daysAgo(5),
    updated_at: hoursAgo(12),
  },
  {
    id: 'SEC-003',
    project_id: 'proj-001',
    title: 'Cross-Site Scripting (XSS) in User Profile',
    description: 'User-controlled input is rendered without proper HTML encoding, allowing XSS attacks.',
    recommendation: 'Sanitize user input and use proper HTML encoding before rendering.',
    file_path: 'src/components/UserProfile.tsx',
    line_start: 89,
    line_end: 89,
    code_snippet: `<div dangerouslySetInnerHTML={{ __html: user.bio }} />`,
    scanner_type: 'sast',
    rule_id: 'xss-001',
    rule_name: 'XSS Prevention',
    severity: 'high',
    cvss_score: 7.5,
    cwe_ids: ['CWE-79'],
    owasp_ids: ['A03:2021'],
    status: 'open',
    triage_status: 'needs_triage',
    sla_deadline: daysFromNow(10),
    sla_status: 'on_track',
    sla_days_remaining: 10,
    branches: ['main', 'develop', 'feature/auth-v2'],
    first_detected_branch: 'main',
    first_detected_commit: 'ghi789',
    first_detected_at: daysAgo(7),
    last_seen_branch: 'main',
    last_seen_commit: 'a1b2c3d4e5f6',
    last_seen_at: hoursAgo(2),
    duplicate_count: 0,
    comments_count: 0,
    created_at: daysAgo(7),
    updated_at: daysAgo(7),
  },
  {
    id: 'SEC-004',
    project_id: 'proj-001',
    title: 'Vulnerable Dependency: lodash < 4.17.21',
    description: 'The lodash package version 4.17.15 is vulnerable to Prototype Pollution (CVE-2021-23337).',
    recommendation: 'Upgrade lodash to version 4.17.21 or later.',
    file_path: 'package.json',
    line_start: 45,
    line_end: 45,
    code_snippet: `"lodash": "^4.17.15"`,
    scanner_type: 'sca',
    rule_id: 'CVE-2021-23337',
    rule_name: 'Prototype Pollution in lodash',
    severity: 'high',
    cvss_score: 7.4,
    cwe_ids: ['CWE-1321'],
    status: 'open',
    triage_status: 'confirmed',
    triaged_by: 'usr-003',
    triaged_at: daysAgo(4),
    assigned_to: 'usr-003',
    assigned_to_name: 'Alice Chen',
    assigned_to_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alice',
    assigned_at: daysAgo(3),
    sla_deadline: daysFromNow(12),
    sla_status: 'on_track',
    sla_days_remaining: 12,
    branches: ['main', 'develop', 'release/v2.0'],
    first_detected_branch: 'main',
    first_detected_commit: 'jkl012',
    first_detected_at: daysAgo(30),
    last_seen_branch: 'main',
    last_seen_commit: 'a1b2c3d4e5f6',
    last_seen_at: hoursAgo(2),
    duplicate_count: 0,
    comments_count: 1,
    created_at: daysAgo(30),
    updated_at: daysAgo(3),
  },
  {
    id: 'SEC-005',
    project_id: 'proj-001',
    title: 'Insecure Deserialization in API Handler',
    description: 'JSON.parse is used without validation on user-controlled input, potentially allowing code injection.',
    recommendation: 'Validate and sanitize input before deserialization. Consider using a schema validator.',
    file_path: 'src/api/handlers/webhook.ts',
    line_start: 67,
    line_end: 70,
    code_snippet: `const payload = JSON.parse(req.body);
processWebhook(payload);`,
    scanner_type: 'sast',
    rule_id: 'insecure-deserialization-001',
    rule_name: 'Insecure Deserialization',
    severity: 'high',
    cvss_score: 7.2,
    cwe_ids: ['CWE-502'],
    owasp_ids: ['A08:2021'],
    status: 'resolved',
    triage_status: 'confirmed',
    triaged_by: 'usr-001',
    triaged_at: daysAgo(15),
    assigned_to: 'usr-001',
    assigned_to_name: 'Jane Doe',
    assigned_to_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jane',
    assigned_at: daysAgo(14),
    sla_status: 'not_applicable',
    branches: ['main'],
    first_detected_branch: 'main',
    first_detected_commit: 'mno345',
    first_detected_at: daysAgo(20),
    last_seen_branch: 'develop',
    last_seen_commit: 'old456',
    last_seen_at: daysAgo(5),
    resolved_at: daysAgo(5),
    resolved_by: 'usr-001',
    resolved_commit: 'fix789',
    resolved_branch: 'main',
    duplicate_count: 0,
    comments_count: 4,
    created_at: daysAgo(20),
    updated_at: daysAgo(5),
  },
  {
    id: 'SEC-006',
    project_id: 'proj-001',
    title: 'Missing Rate Limiting on Authentication Endpoint',
    description: 'The /api/auth/login endpoint lacks rate limiting, making it vulnerable to brute force attacks.',
    recommendation: 'Implement rate limiting using a middleware like express-rate-limit.',
    file_path: 'src/api/routes/auth.ts',
    line_start: 12,
    line_end: 25,
    scanner_type: 'sast',
    rule_id: 'missing-rate-limit-001',
    rule_name: 'Rate Limiting Required',
    severity: 'medium',
    cvss_score: 5.3,
    cwe_ids: ['CWE-307'],
    owasp_ids: ['A07:2021'],
    status: 'open',
    triage_status: 'confirmed',
    triaged_by: 'usr-002',
    triaged_at: daysAgo(10),
    sla_deadline: daysFromNow(20),
    sla_status: 'on_track',
    sla_days_remaining: 20,
    branches: ['main', 'develop'],
    first_detected_branch: 'main',
    first_detected_commit: 'pqr678',
    first_detected_at: daysAgo(45),
    last_seen_branch: 'main',
    last_seen_commit: 'a1b2c3d4e5f6',
    last_seen_at: hoursAgo(2),
    duplicate_count: 0,
    comments_count: 2,
    created_at: daysAgo(45),
    updated_at: daysAgo(10),
  },
  {
    id: 'SEC-007',
    project_id: 'proj-001',
    title: 'Exposed Kubernetes Secrets in IaC',
    description: 'Kubernetes secret is not encrypted at rest in the manifest file.',
    recommendation: 'Use sealed-secrets or external secret management solutions.',
    file_path: 'k8s/secrets.yaml',
    line_start: 8,
    line_end: 12,
    code_snippet: `data:
  db-password: YWRtaW4xMjM=
  api-key: c2VjcmV0LWFwaS1rZXk=`,
    scanner_type: 'iac',
    rule_id: 'k8s-secrets-001',
    rule_name: 'Kubernetes Secrets Encryption',
    severity: 'medium',
    cvss_score: 5.5,
    cwe_ids: ['CWE-312'],
    status: 'open',
    triage_status: 'needs_triage',
    sla_deadline: daysFromNow(25),
    sla_status: 'on_track',
    sla_days_remaining: 25,
    branches: ['main', 'develop'],
    first_detected_branch: 'main',
    first_detected_commit: 'stu901',
    first_detected_at: daysAgo(14),
    last_seen_branch: 'main',
    last_seen_commit: 'a1b2c3d4e5f6',
    last_seen_at: hoursAgo(2),
    duplicate_count: 0,
    comments_count: 0,
    created_at: daysAgo(14),
    updated_at: daysAgo(14),
  },
  {
    id: 'SEC-008',
    project_id: 'proj-001',
    title: 'Container Running as Root',
    description: 'Docker container is configured to run as root user, which poses security risks.',
    recommendation: 'Create a non-root user in Dockerfile and use USER directive.',
    file_path: 'Dockerfile',
    line_start: 1,
    line_end: 1,
    code_snippet: `FROM node:18`,
    scanner_type: 'container',
    rule_id: 'container-root-001',
    rule_name: 'Container Root User',
    severity: 'medium',
    cvss_score: 5.0,
    cwe_ids: ['CWE-250'],
    status: 'open',
    triage_status: 'wont_fix',
    triage_reason: 'Accepted risk for internal development environment',
    triaged_by: 'usr-004',
    triaged_at: daysAgo(20),
    sla_status: 'not_applicable',
    branches: ['main', 'develop', 'release/v2.0'],
    first_detected_branch: 'main',
    first_detected_commit: 'vwx234',
    first_detected_at: daysAgo(60),
    last_seen_branch: 'main',
    last_seen_commit: 'a1b2c3d4e5f6',
    last_seen_at: hoursAgo(2),
    duplicate_count: 0,
    comments_count: 1,
    created_at: daysAgo(60),
    updated_at: daysAgo(20),
  },
  {
    id: 'SEC-009',
    project_id: 'proj-001',
    title: 'Weak Password Requirements',
    description: 'Password validation allows passwords shorter than 8 characters.',
    recommendation: 'Enforce minimum password length of 12 characters with complexity requirements.',
    file_path: 'src/auth/validation.ts',
    line_start: 34,
    line_end: 34,
    code_snippet: `const MIN_PASSWORD_LENGTH = 6;`,
    scanner_type: 'sast',
    rule_id: 'weak-password-001',
    rule_name: 'Password Strength',
    severity: 'low',
    cvss_score: 4.0,
    cwe_ids: ['CWE-521'],
    status: 'open',
    triage_status: 'false_positive',
    triage_reason: 'This is only used for internal testing environment',
    triaged_by: 'usr-001',
    triaged_at: daysAgo(5),
    sla_status: 'not_applicable',
    branches: ['main'],
    first_detected_branch: 'main',
    first_detected_commit: 'yza567',
    first_detected_at: daysAgo(90),
    last_seen_branch: 'main',
    last_seen_commit: 'a1b2c3d4e5f6',
    last_seen_at: hoursAgo(2),
    duplicate_count: 0,
    comments_count: 1,
    created_at: daysAgo(90),
    updated_at: daysAgo(5),
  },
  {
    id: 'SEC-010',
    project_id: 'proj-001',
    title: 'Missing Security Headers',
    description: 'HTTP response is missing security headers: X-Content-Type-Options, X-Frame-Options.',
    recommendation: 'Add security headers using helmet middleware.',
    file_path: 'src/middleware/security.ts',
    line_start: 1,
    line_end: 10,
    scanner_type: 'dast',
    rule_id: 'security-headers-001',
    rule_name: 'Security Headers',
    severity: 'low',
    cvss_score: 3.5,
    cwe_ids: ['CWE-693'],
    status: 'open',
    triage_status: 'needs_triage',
    sla_deadline: daysFromNow(55),
    sla_status: 'on_track',
    sla_days_remaining: 55,
    branches: ['main', 'develop'],
    first_detected_branch: 'main',
    first_detected_commit: 'bcd890',
    first_detected_at: daysAgo(7),
    last_seen_branch: 'main',
    last_seen_commit: 'a1b2c3d4e5f6',
    last_seen_at: hoursAgo(2),
    duplicate_count: 0,
    comments_count: 0,
    created_at: daysAgo(7),
    updated_at: daysAgo(7),
  },
]

// ============================================
// Mock Activity Log for proj-001
// ============================================

export const mockActivities: ActivityLog[] = [
  {
    id: 'act-001',
    project_id: 'proj-001',
    timestamp: hoursAgo(2),
    actor_id: 'system',
    actor_name: 'GitHub Scanner',
    actor_type: 'system',
    action: 'scan_completed',
    entity_type: 'scan',
    entity_id: 'scan-101',
    entity_name: 'main branch scan',
    scan_summary: {
      branch: 'main',
      findings_new: 0,
      findings_resolved: 2,
      findings_total: 46,
      duration_seconds: 225,
      quality_gate_passed: true,
    },
  },
  {
    id: 'act-002',
    project_id: 'proj-001',
    timestamp: hoursAgo(4),
    actor_id: 'usr-001',
    actor_name: 'Jane Doe',
    actor_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jane',
    actor_type: 'user',
    action: 'finding_status_changed',
    entity_type: 'finding',
    entity_id: 'SEC-002',
    entity_name: 'Hardcoded AWS Secret Key',
    changes: [
      { field: 'status', old_value: 'open', new_value: 'in_progress' },
    ],
    comment: 'Starting to work on removing the hardcoded secret',
  },
  {
    id: 'act-003',
    project_id: 'proj-001',
    timestamp: hoursAgo(6),
    actor_id: 'system',
    actor_name: 'GitHub Scanner',
    actor_type: 'system',
    action: 'scan_completed',
    entity_type: 'scan',
    entity_id: 'scan-105',
    entity_name: 'hotfix/login-bypass scan',
    scan_summary: {
      branch: 'hotfix/login-bypass',
      findings_new: 0,
      findings_resolved: 2,
      findings_total: 44,
      duration_seconds: 180,
      quality_gate_passed: true,
    },
  },
  {
    id: 'act-004',
    project_id: 'proj-001',
    timestamp: hoursAgo(8),
    actor_id: 'usr-002',
    actor_name: 'John Smith',
    actor_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=john',
    actor_type: 'user',
    action: 'finding_assigned',
    entity_type: 'finding',
    entity_id: 'SEC-002',
    entity_name: 'Hardcoded AWS Secret Key',
    changes: [
      { field: 'assigned_to', old_value: null, new_value: 'John Smith' },
    ],
  },
  {
    id: 'act-005',
    project_id: 'proj-001',
    timestamp: hoursAgo(12),
    actor_id: 'usr-001',
    actor_name: 'Jane Doe',
    actor_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jane',
    actor_type: 'user',
    action: 'finding_commented',
    entity_type: 'finding',
    entity_id: 'SEC-001',
    entity_name: 'SQL Injection in User Login',
    comment: 'I have started working on the fix. Will use parameterized queries.',
  },
  {
    id: 'act-006',
    project_id: 'proj-001',
    timestamp: daysAgo(1),
    actor_id: 'webhook',
    actor_name: 'GitHub Webhook',
    actor_type: 'webhook',
    action: 'pr_merged',
    entity_type: 'pr',
    entity_id: 'pr-2134',
    entity_name: 'PR #2134',
    pr_info: {
      number: 2134,
      title: 'fix: resolve authentication race condition',
      url: 'https://github.com/acme-corp/api-gateway/pull/2134',
      source_branch: 'hotfix/auth-race',
      target_branch: 'main',
    },
  },
  {
    id: 'act-007',
    project_id: 'proj-001',
    timestamp: daysAgo(1),
    actor_id: 'system',
    actor_name: 'GitHub Scanner',
    actor_type: 'system',
    action: 'scan_completed',
    entity_type: 'scan',
    entity_id: 'scan-103',
    entity_name: 'feature/auth-v2 scan',
    scan_summary: {
      branch: 'feature/auth-v2',
      findings_new: 2,
      findings_resolved: 0,
      findings_total: 48,
      duration_seconds: 195,
      quality_gate_passed: true,
    },
  },
  {
    id: 'act-008',
    project_id: 'proj-001',
    timestamp: daysAgo(2),
    actor_id: 'usr-001',
    actor_name: 'Jane Doe',
    actor_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jane',
    actor_type: 'user',
    action: 'finding_triaged',
    entity_type: 'finding',
    entity_id: 'SEC-001',
    entity_name: 'SQL Injection in User Login',
    changes: [
      { field: 'triage_status', old_value: 'needs_triage', new_value: 'confirmed' },
    ],
    comment: 'Confirmed as a real issue. Need to fix ASAP.',
  },
  {
    id: 'act-009',
    project_id: 'proj-001',
    timestamp: daysAgo(3),
    actor_id: 'automation',
    actor_name: 'SLA Monitor',
    actor_type: 'automation',
    action: 'notification_sent',
    entity_type: 'finding',
    entity_id: 'SEC-001',
    entity_name: 'SQL Injection in User Login',
    comment: 'SLA warning: 80% of remediation time has elapsed',
  },
  {
    id: 'act-010',
    project_id: 'proj-001',
    timestamp: daysAgo(5),
    actor_id: 'usr-001',
    actor_name: 'Jane Doe',
    actor_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jane',
    actor_type: 'user',
    action: 'finding_resolved',
    entity_type: 'finding',
    entity_id: 'SEC-005',
    entity_name: 'Insecure Deserialization in API Handler',
    changes: [
      { field: 'status', old_value: 'in_progress', new_value: 'resolved' },
    ],
    comment: 'Fixed by implementing JSON schema validation',
  },
  {
    id: 'act-011',
    project_id: 'proj-001',
    timestamp: daysAgo(7),
    actor_id: 'system',
    actor_name: 'GitHub Scanner',
    actor_type: 'system',
    action: 'finding_created',
    entity_type: 'finding',
    entity_id: 'SEC-003',
    entity_name: 'Cross-Site Scripting (XSS) in User Profile',
  },
  {
    id: 'act-012',
    project_id: 'proj-001',
    timestamp: daysAgo(10),
    actor_id: 'system',
    actor_name: 'GitHub Scanner',
    actor_type: 'system',
    action: 'finding_created',
    entity_type: 'finding',
    entity_id: 'SEC-001',
    entity_name: 'SQL Injection in User Login',
  },
  {
    id: 'act-013',
    project_id: 'proj-001',
    timestamp: daysAgo(14),
    actor_id: 'usr-004',
    actor_name: 'Bob Wilson',
    actor_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bob',
    actor_type: 'user',
    action: 'branch_created',
    entity_type: 'branch',
    entity_id: 'branch-003',
    entity_name: 'feature/auth-v2',
  },
  {
    id: 'act-014',
    project_id: 'proj-001',
    timestamp: daysAgo(20),
    actor_id: 'usr-004',
    actor_name: 'Bob Wilson',
    actor_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bob',
    actor_type: 'user',
    action: 'finding_triaged',
    entity_type: 'finding',
    entity_id: 'SEC-008',
    entity_name: 'Container Running as Root',
    changes: [
      { field: 'triage_status', old_value: 'needs_triage', new_value: 'wont_fix' },
    ],
    comment: 'Accepted risk for internal development environment',
  },
  {
    id: 'act-015',
    project_id: 'proj-001',
    timestamp: daysAgo(30),
    actor_id: 'webhook',
    actor_name: 'Jira Integration',
    actor_type: 'webhook',
    action: 'issue_created',
    entity_type: 'integration',
    entity_id: 'jira-SEC-1234',
    entity_name: 'Jira ticket SEC-1234',
    metadata: {
      jira_key: 'SEC-1234',
      finding_id: 'SEC-001',
    },
  },
]

// ============================================
// Mock SLA Policy
// ============================================

export const mockSLAPolicy: SLAPolicy = {
  id: 'sla-001',
  project_id: 'proj-001',
  tenant_id: 'tenant-001',
  name: 'Standard Security SLA',
  description: 'Default SLA policy for security findings based on severity',
  is_default: false,
  rules: [
    { severity: 'critical', days_to_remediate: 2, warning_threshold_percent: 80 },
    { severity: 'high', days_to_remediate: 15, warning_threshold_percent: 80 },
    { severity: 'medium', days_to_remediate: 30, warning_threshold_percent: 80 },
    { severity: 'low', days_to_remediate: 60, warning_threshold_percent: 80 },
    { severity: 'info', days_to_remediate: 90, warning_threshold_percent: 80 },
  ],
  escalation_enabled: true,
  escalation_rules: [
    {
      trigger: 'warning',
      notify_channels: ['#security-alerts'],
    },
    {
      trigger: 'overdue',
      notify_users: ['usr-001'],
      notify_channels: ['#security-alerts'],
    },
    {
      trigger: 'exceeded',
      notify_users: ['usr-001', 'usr-005'],
      notify_channels: ['#security-alerts', '#engineering-leads'],
      auto_assign_to: 'usr-005',
    },
  ],
  created_at: daysAgo(90),
  updated_at: daysAgo(30),
}

// ============================================
// Helper: Get project detail data
// ============================================

export function getProjectDetailMockData(projectId: string) {
  return {
    branches: mockBranches.filter(b => b.project_id === projectId),
    findings: mockFindings.filter(f => f.project_id === projectId),
    activities: mockActivities.filter(a => a.project_id === projectId),
    slaPolicy: mockSLAPolicy,
  }
}

// ============================================
// Helper: Get findings stats
// ============================================

export function getFindingsStats(findings: FindingDetail[]): FindingsSummary {
  const summary: FindingsSummary = {
    total: findings.length,
    by_severity: { critical: 0, high: 0, medium: 0, low: 0, info: 0 },
    by_status: { open: 0, confirmed: 0, in_progress: 0, resolved: 0, false_positive: 0, accepted_risk: 0 },
    by_type: { sast: 0, sca: 0, secret: 0, iac: 0, container: 0, dast: 0 },
  }

  findings.forEach(f => {
    summary.by_severity[f.severity]++
    summary.by_status[f.status]++
    summary.by_type[f.scanner_type]++
  })

  return summary
}

// ============================================
// Helper: Get overdue findings count
// ============================================

export function getOverdueFindingsCount(findings: FindingDetail[]): number {
  return findings.filter(f =>
    f.sla_status === 'overdue' || f.sla_status === 'exceeded'
  ).length
}

// ============================================
// Helper: Get SLA warnings count
// ============================================

export function getSLAWarningsCount(findings: FindingDetail[]): number {
  return findings.filter(f => f.sla_status === 'warning').length
}
